// services/offers.ts
import { createPublicClient as createClient, isSupabaseConfigured } from "@/lib/supabase/server";
import { Offer, OfferFilters, PaginatedOffers } from "@/types";
import { fetchWithTimeout } from "@/lib/fetchWithTimeout";

export const FALLBACK_OFFERS: Offer[] = [
  {
    "id": "b1111111-1111-4111-a111-111111111101",
    "slug": "sbb-ga-night",
    "title_de": "SBB GA Night für CHF 99.– / Jahr (unter 25 J.)",
    "title_fr": "SBB GA Night für CHF 99.– / Jahr (unter 25 J.)",
    "title_it": "SBB GA Night für CHF 99.– / Jahr (unter 25 J.)",
    "description_de": "Freie Fahrt im gesamten SBB-Netz jeden Abend ab 19:00 Uhr bis 05:00 Uhr morgens in der 2. Klasse.",
    "description_fr": "Freie Fahrt im gesamten SBB-Netz jeden Abend ab 19:00 Uhr bis 05:00 Uhr morgens in der 2. Klasse.",
    "description_it": "Freie Fahrt im gesamten SBB-Netz jeden Abend ab 19:00 Uhr bis 05:00 Uhr morgens in der 2. Klasse.",
    "conditions_de": "Gültig für Jugendliche & Studierende in der Schweiz bis 25 Jahre.",
    "how_to_get_de": "1. Angebot auswählen\n2. Über den Link registrieren oder Legi vorweisen\n3. Rabatt sofort einlösen",
    "brand_id": "b-sbb",
    "brand": {
      "id": "b-sbb",
      "slug": "sbb",
      "name": "SBB CFF FFS",
      "logo_url": null,
      "description_de": "Offizieller Partner SBB CFF FFS in der Schweiz",
      "website_url": "https://www.sbb.ch",
      "categories": [
        "reisen"
      ],
      "created_at": "2026-09-26T02:48:56.622Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-reisen",
    "category": {
      "id": "cat-reisen",
      "slug": "reisen",
      "name_de": "Reisen & ÖV",
      "name_fr": "Reisen & ÖV",
      "name_it": "Reisen & ÖV",
      "icon": "🚆",
      "description_de": "Angebote in Reisen & ÖV",
      "sort_order": 1,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 350,
    "young_price": 99,
    "discount_percent": 72,
    "discount_amount": 251,
    "advantage_type": "reduced_price",
    "age_min": 16,
    "age_max": 25,
    "student_required": false,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.sbb.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "RABATT",
      "SCHWEIZWEIT",
      "VERIFIZIERT"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": null,
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 120,
    "click_count": 45,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111102",
    "slug": "sbb-halbtax-jugend",
    "title_de": "SBB Halbtax Jugend für CHF 120.– im 1. Jahr",
    "title_fr": "SBB Halbtax Jugend für CHF 120.– im 1. Jahr",
    "title_it": "SBB Halbtax Jugend für CHF 120.– im 1. Jahr",
    "description_de": "Halbiere den Ticketpreis für fast alle Zug-, Bus- und Tramfahrten in der gesamten Schweiz.",
    "description_fr": "Halbiere den Ticketpreis für fast alle Zug-, Bus- und Tramfahrten in der gesamten Schweiz.",
    "description_it": "Halbiere den Ticketpreis für fast alle Zug-, Bus- und Tramfahrten in der gesamten Schweiz.",
    "conditions_de": "Gültig für Jugendliche & Studierende in der Schweiz bis 25 Jahre.",
    "how_to_get_de": "1. Angebot auswählen\n2. Über den Link registrieren oder Legi vorweisen\n3. Rabatt sofort einlösen",
    "brand_id": "b-sbb",
    "brand": {
      "id": "b-sbb",
      "slug": "sbb",
      "name": "SBB CFF FFS",
      "logo_url": null,
      "description_de": "Offizieller Partner SBB CFF FFS in der Schweiz",
      "website_url": "https://www.sbb.ch",
      "categories": [
        "reisen"
      ],
      "created_at": "2026-09-26T02:48:56.626Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-reisen",
    "category": {
      "id": "cat-reisen",
      "slug": "reisen",
      "name_de": "Reisen & ÖV",
      "name_fr": "Reisen & ÖV",
      "name_it": "Reisen & ÖV",
      "icon": "🚆",
      "description_de": "Angebote in Reisen & ÖV",
      "sort_order": 1,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 190,
    "young_price": 120,
    "discount_percent": 37,
    "discount_amount": 70,
    "advantage_type": "reduced_price",
    "age_min": 16,
    "age_max": 25,
    "student_required": false,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.sbb.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "RABATT",
      "SCHWEIZWEIT",
      "VERIFIZIERT"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": null,
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 120,
    "click_count": 45,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111103",
    "slug": "swisspass-partner-vorteile",
    "title_de": "Swisspass Partner-Vorteile & PubliBike Rabatte",
    "title_fr": "Swisspass Partner-Vorteile & PubliBike Rabatte",
    "title_it": "Swisspass Partner-Vorteile & PubliBike Rabatte",
    "description_de": "Kostenlose Verknüpfung von PubliBike Leihvelos und Mobility Carsharing auf deinem Swisspass.",
    "description_fr": "Kostenlose Verknüpfung von PubliBike Leihvelos und Mobility Carsharing auf deinem Swisspass.",
    "description_it": "Kostenlose Verknüpfung von PubliBike Leihvelos und Mobility Carsharing auf deinem Swisspass.",
    "conditions_de": "Gültig für Jugendliche & Studierende in der Schweiz bis 30 Jahre.",
    "how_to_get_de": "1. Angebot auswählen\n2. Über den Link registrieren oder Legi vorweisen\n3. Rabatt sofort einlösen",
    "brand_id": "b-swisspass",
    "brand": {
      "id": "b-swisspass",
      "slug": "swisspass",
      "name": "Alliance Swisspass",
      "logo_url": null,
      "description_de": "Offizieller Partner Alliance Swisspass in der Schweiz",
      "website_url": "https://www.swisspass.ch",
      "categories": [
        "reisen"
      ],
      "created_at": "2026-09-26T02:48:56.626Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-reisen",
    "category": {
      "id": "cat-reisen",
      "slug": "reisen",
      "name_de": "Reisen & ÖV",
      "name_fr": "Reisen & ÖV",
      "name_it": "Reisen & ÖV",
      "icon": "🚆",
      "description_de": "Angebote in Reisen & ÖV",
      "sort_order": 1,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 50,
    "young_price": 0,
    "discount_percent": 100,
    "discount_amount": 50,
    "advantage_type": "free",
    "age_min": 16,
    "age_max": 30,
    "student_required": false,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.swisspass.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "KOSTENLOS",
      "SCHWEIZWEIT",
      "VERIFIZIERT"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": null,
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 120,
    "click_count": 45,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111104",
    "slug": "neon-free-banking",
    "title_de": "Neon Free Girokonto: CHF 0.– Kartengebühren",
    "title_fr": "Neon Free Girokonto: CHF 0.– Kartengebühren",
    "title_it": "Neon Free Girokonto: CHF 0.– Kartengebühren",
    "description_de": "Schweizer Smartphone-Konto ohne Monatsgebühr inklusive Mastercard und günstigen Auslandstransaktionen.",
    "description_fr": "Schweizer Smartphone-Konto ohne Monatsgebühr inklusive Mastercard und günstigen Auslandstransaktionen.",
    "description_it": "Schweizer Smartphone-Konto ohne Monatsgebühr inklusive Mastercard und günstigen Auslandstransaktionen.",
    "conditions_de": "Gültig für Jugendliche & Studierende in der Schweiz bis 30 Jahre.",
    "how_to_get_de": "1. Angebot auswählen\n2. Über den Link registrieren oder Legi vorweisen\n3. Rabatt sofort einlösen",
    "brand_id": "b-neon",
    "brand": {
      "id": "b-neon",
      "slug": "neon",
      "name": "Neon Bank",
      "logo_url": null,
      "description_de": "Offizieller Partner Neon Bank in der Schweiz",
      "website_url": "https://www.neon.ch",
      "categories": [
        "finanzen"
      ],
      "created_at": "2026-09-26T02:48:56.626Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-finanzen",
    "category": {
      "id": "cat-finanzen",
      "slug": "finanzen",
      "name_de": "Finanzen & Neobanken",
      "name_fr": "Finanzen & Neobanken",
      "name_it": "Finanzen & Neobanken",
      "icon": "💳",
      "description_de": "Angebote in Finanzen & Neobanken",
      "sort_order": 1,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 120,
    "young_price": 0,
    "discount_percent": 100,
    "discount_amount": 120,
    "advantage_type": "free",
    "age_min": 16,
    "age_max": 30,
    "student_required": false,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.neon.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "KOSTENLOS",
      "SCHWEIZWEIT",
      "VERIFIZIERT"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": null,
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 120,
    "click_count": 45,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111105",
    "slug": "yuh-banking-app",
    "title_de": "Yuh Gratis-Konto mit Zinsen & Trading",
    "title_fr": "Yuh Gratis-Konto mit Zinsen & Trading",
    "title_it": "Yuh Gratis-Konto mit Zinsen & Trading",
    "description_de": "Kostenloses Multiwährungskonto von PostFinance & Swissquote mit Zinsen auf deine Ersparnisse.",
    "description_fr": "Kostenloses Multiwährungskonto von PostFinance & Swissquote mit Zinsen auf deine Ersparnisse.",
    "description_it": "Kostenloses Multiwährungskonto von PostFinance & Swissquote mit Zinsen auf deine Ersparnisse.",
    "conditions_de": "Gültig für Jugendliche & Studierende in der Schweiz bis 30 Jahre.",
    "how_to_get_de": "1. Angebot auswählen\n2. Über den Link registrieren oder Legi vorweisen\n3. Rabatt sofort einlösen",
    "brand_id": "b-yuh",
    "brand": {
      "id": "b-yuh",
      "slug": "yuh",
      "name": "Yuh Schweiz",
      "logo_url": null,
      "description_de": "Offizieller Partner Yuh Schweiz in der Schweiz",
      "website_url": "https://www.yuh.ch",
      "categories": [
        "finanzen"
      ],
      "created_at": "2026-09-26T02:48:56.626Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-finanzen",
    "category": {
      "id": "cat-finanzen",
      "slug": "finanzen",
      "name_de": "Finanzen & Neobanken",
      "name_fr": "Finanzen & Neobanken",
      "name_it": "Finanzen & Neobanken",
      "icon": "💳",
      "description_de": "Angebote in Finanzen & Neobanken",
      "sort_order": 1,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 100,
    "young_price": 0,
    "discount_percent": 100,
    "discount_amount": 100,
    "advantage_type": "free",
    "age_min": 16,
    "age_max": 30,
    "student_required": false,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.yuh.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "KOSTENLOS",
      "SCHWEIZWEIT",
      "VERIFIZIERT"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": null,
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 120,
    "click_count": 45,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111106",
    "slug": "zkb-young-paket",
    "title_de": "ZKB young Konto inklusive Gratis-Nachtschwärmer",
    "title_fr": "ZKB young Konto inklusive Gratis-Nachtschwärmer",
    "title_it": "ZKB young Konto inklusive Gratis-Nachtschwärmer",
    "description_de": "Kostenloses Jugendkonto der Zürcher Kantonalbank mit ZKB Nachtschwärmer Ticket im ZVV.",
    "description_fr": "Kostenloses Jugendkonto der Zürcher Kantonalbank mit ZKB Nachtschwärmer Ticket im ZVV.",
    "description_it": "Kostenloses Jugendkonto der Zürcher Kantonalbank mit ZKB Nachtschwärmer Ticket im ZVV.",
    "conditions_de": "Gültig für Jugendliche & Studierende in der Schweiz bis 25 Jahre.",
    "how_to_get_de": "1. Angebot auswählen\n2. Über den Link registrieren oder Legi vorweisen\n3. Rabatt sofort einlösen",
    "brand_id": "b-zkb",
    "brand": {
      "id": "b-zkb",
      "slug": "zkb",
      "name": "Zürcher Kantonalbank",
      "logo_url": null,
      "description_de": "Offizieller Partner Zürcher Kantonalbank in der Schweiz",
      "website_url": "https://www.zkb.ch",
      "categories": [
        "finanzen"
      ],
      "created_at": "2026-09-26T02:48:56.626Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-finanzen",
    "category": {
      "id": "cat-finanzen",
      "slug": "finanzen",
      "name_de": "Finanzen & Neobanken",
      "name_fr": "Finanzen & Neobanken",
      "name_it": "Finanzen & Neobanken",
      "icon": "💳",
      "description_de": "Angebote in Finanzen & Neobanken",
      "sort_order": 1,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 90,
    "young_price": 0,
    "discount_percent": 100,
    "discount_amount": 90,
    "advantage_type": "free",
    "age_min": 16,
    "age_max": 25,
    "student_required": false,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.zkb.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "KOSTENLOS",
      "SCHWEIZWEIT",
      "VERIFIZIERT"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": null,
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 120,
    "click_count": 45,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111107",
    "slug": "ipv-praemienverbilligung-schweiz",
    "title_de": "Krankenkassen-Prämienverbilligung (IPV): Bis zu 80% Kantonszuschuss",
    "title_fr": "Krankenkassen-Prämienverbilligung (IPV): Bis zu 80% Kantonszuschuss",
    "title_it": "Krankenkassen-Prämienverbilligung (IPV): Bis zu 80% Kantonszuschuss",
    "description_de": "Staatlicher Zuschuss zur Reduktion der monatlichen Grundversicherungsprämie für Studierende & Auszubildende.",
    "description_fr": "Staatlicher Zuschuss zur Reduktion der monatlichen Grundversicherungsprämie für Studierende & Auszubildende.",
    "description_it": "Staatlicher Zuschuss zur Reduktion der monatlichen Grundversicherungsprämie für Studierende & Auszubildende.",
    "conditions_de": "Gültig für Jugendliche & Studierende in der Schweiz bis 30 Jahre.",
    "how_to_get_de": "1. Angebot auswählen\n2. Über den Link registrieren oder Legi vorweisen\n3. Rabatt sofort einlösen",
    "brand_id": "b-sva",
    "brand": {
      "id": "b-sva",
      "slug": "sva",
      "name": "SVA / Kantonale Sozialversicherung",
      "logo_url": null,
      "description_de": "Offizieller Partner SVA / Kantonale Sozialversicherung in der Schweiz",
      "website_url": "https://www.sva.ch",
      "categories": [
        "krankenkasse"
      ],
      "created_at": "2026-09-26T02:48:56.626Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-krankenkasse",
    "category": {
      "id": "cat-krankenkasse",
      "slug": "krankenkasse",
      "name_de": "Krankenkasse & IPV",
      "name_fr": "Krankenkasse & IPV",
      "name_it": "Krankenkasse & IPV",
      "icon": "🩺",
      "description_de": "Angebote in Krankenkasse & IPV",
      "sort_order": 1,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 350,
    "young_price": 50,
    "discount_percent": 86,
    "discount_amount": 300,
    "advantage_type": "reduced_price",
    "age_min": 16,
    "age_max": 30,
    "student_required": true,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.sva.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "RABATT",
      "SCHWEIZWEIT",
      "VERIFIZIERT"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": null,
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 120,
    "click_count": 45,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111108",
    "slug": "sanitas-fitness-cashback",
    "title_de": "Sanitas Sport-Cashback: Bis zu CHF 500.– für ASVZ & Gym",
    "title_fr": "Sanitas Sport-Cashback: Bis zu CHF 500.– für ASVZ & Gym",
    "title_it": "Sanitas Sport-Cashback: Bis zu CHF 500.– für ASVZ & Gym",
    "description_de": "Zusatzversicherung erstattet Beiträge an Hochschulsport (ASVZ/UNISPORT) und zertifizierte Fitnessstudios.",
    "description_fr": "Zusatzversicherung erstattet Beiträge an Hochschulsport (ASVZ/UNISPORT) und zertifizierte Fitnessstudios.",
    "description_it": "Zusatzversicherung erstattet Beiträge an Hochschulsport (ASVZ/UNISPORT) und zertifizierte Fitnessstudios.",
    "conditions_de": "Gültig für Jugendliche & Studierende in der Schweiz bis 30 Jahre.",
    "how_to_get_de": "1. Angebot auswählen\n2. Über den Link registrieren oder Legi vorweisen\n3. Rabatt sofort einlösen",
    "brand_id": "b-sanitas",
    "brand": {
      "id": "b-sanitas",
      "slug": "sanitas",
      "name": "Sanitas Krankenversicherung",
      "logo_url": null,
      "description_de": "Offizieller Partner Sanitas Krankenversicherung in der Schweiz",
      "website_url": "https://www.sanitas.ch",
      "categories": [
        "krankenkasse"
      ],
      "created_at": "2026-09-26T02:48:56.626Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-krankenkasse",
    "category": {
      "id": "cat-krankenkasse",
      "slug": "krankenkasse",
      "name_de": "Krankenkasse & IPV",
      "name_fr": "Krankenkasse & IPV",
      "name_it": "Krankenkasse & IPV",
      "icon": "🩺",
      "description_de": "Angebote in Krankenkasse & IPV",
      "sort_order": 1,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 500,
    "young_price": 0,
    "discount_percent": 100,
    "discount_amount": 500,
    "advantage_type": "free",
    "age_min": 16,
    "age_max": 30,
    "student_required": false,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.sanitas.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "KOSTENLOS",
      "SCHWEIZWEIT",
      "VERIFIZIERT"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": null,
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 120,
    "click_count": 45,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111109",
    "slug": "woko-studenten-wgs",
    "title_de": "WOKO Zürcher Studentenzimmer ab CHF 500.– / Monat",
    "title_fr": "WOKO Zürcher Studentenzimmer ab CHF 500.– / Monat",
    "title_it": "WOKO Zürcher Studentenzimmer ab CHF 500.– / Monat",
    "description_de": "Günstige möblierte und unmöblierte WG-Zimmer für UZH, ETH und ZHAW Studierende.",
    "description_fr": "Günstige möblierte und unmöblierte WG-Zimmer für UZH, ETH und ZHAW Studierende.",
    "description_it": "Günstige möblierte und unmöblierte WG-Zimmer für UZH, ETH und ZHAW Studierende.",
    "conditions_de": "Gültig für Jugendliche & Studierende in der Schweiz bis 30 Jahre.",
    "how_to_get_de": "1. Angebot auswählen\n2. Über den Link registrieren oder Legi vorweisen\n3. Rabatt sofort einlösen",
    "brand_id": "b-woko",
    "brand": {
      "id": "b-woko",
      "slug": "woko",
      "name": "WOKO Studentische Wohngenossenschaft",
      "logo_url": null,
      "description_de": "Offizieller Partner WOKO Studentische Wohngenossenschaft in der Schweiz",
      "website_url": "https://www.woko.ch",
      "categories": [
        "wohnen"
      ],
      "created_at": "2026-09-26T02:48:56.627Z",
      "updated_at": "2026-09-26T02:48:56.627Z"
    },
    "category_id": "cat-wohnen",
    "category": {
      "id": "cat-wohnen",
      "slug": "wohnen",
      "name_de": "Miete & WGs",
      "name_fr": "Miete & WGs",
      "name_it": "Miete & WGs",
      "icon": "🏠",
      "description_de": "Angebote in Miete & WGs",
      "sort_order": 1,
      "created_at": "2026-09-26T02:48:56.627Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 1100,
    "young_price": 500,
    "discount_percent": 55,
    "discount_amount": 600,
    "advantage_type": "reduced_price",
    "age_min": 16,
    "age_max": 30,
    "student_required": true,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.woko.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.627Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "RABATT",
      "SCHWEIZWEIT",
      "VERIFIZIERT"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": null,
    "checked_at": "2026-09-26T02:48:56.627Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 120,
    "click_count": 45,
    "created_at": "2026-09-26T02:48:56.627Z",
    "updated_at": "2026-09-26T02:48:56.627Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111110",
    "slug": "fmel-lausanne-housing",
    "title_de": "FMEL Student Housing Lausanne ab CHF 480.–",
    "title_fr": "FMEL Student Housing Lausanne ab CHF 480.–",
    "title_it": "FMEL Student Housing Lausanne ab CHF 480.–",
    "description_de": "Wohnheimzimmer direkt am UNIL & EPFL Campus Dorigny in Lausanne.",
    "description_fr": "Wohnheimzimmer direkt am UNIL & EPFL Campus Dorigny in Lausanne.",
    "description_it": "Wohnheimzimmer direkt am UNIL & EPFL Campus Dorigny in Lausanne.",
    "conditions_de": "Gültig für Jugendliche & Studierende in der Schweiz bis 30 Jahre.",
    "how_to_get_de": "1. Angebot auswählen\n2. Über den Link registrieren oder Legi vorweisen\n3. Rabatt sofort einlösen",
    "brand_id": "b-fmel",
    "brand": {
      "id": "b-fmel",
      "slug": "fmel",
      "name": "FMEL Lausanne",
      "logo_url": null,
      "description_de": "Offizieller Partner FMEL Lausanne in der Schweiz",
      "website_url": "https://www.fmel.ch",
      "categories": [
        "wohnen"
      ],
      "created_at": "2026-09-26T02:48:56.627Z",
      "updated_at": "2026-09-26T02:48:56.627Z"
    },
    "category_id": "cat-wohnen",
    "category": {
      "id": "cat-wohnen",
      "slug": "wohnen",
      "name_de": "Miete & WGs",
      "name_fr": "Miete & WGs",
      "name_it": "Miete & WGs",
      "icon": "🏠",
      "description_de": "Angebote in Miete & WGs",
      "sort_order": 1,
      "created_at": "2026-09-26T02:48:56.627Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 1050,
    "young_price": 480,
    "discount_percent": 54,
    "discount_amount": 570,
    "advantage_type": "reduced_price",
    "age_min": 16,
    "age_max": 30,
    "student_required": true,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.fmel.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.627Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "RABATT",
      "SCHWEIZWEIT",
      "VERIFIZIERT"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": null,
    "checked_at": "2026-09-26T02:48:56.627Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 120,
    "click_count": 45,
    "created_at": "2026-09-26T02:48:56.627Z",
    "updated_at": "2026-09-26T02:48:56.627Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111111",
    "slug": "salt-youth-mobile",
    "title_de": "Salt Youth: Unlimitiertes 5G in CH für CHF 24.95",
    "title_fr": "Salt Youth: Unlimitiertes 5G in CH für CHF 24.95",
    "title_it": "Salt Youth: Unlimitiertes 5G in CH für CHF 24.95",
    "description_de": "Unlimitiertes Highspeed 5G Surfen und Telefonieren in der ganzen Schweiz unter 30 Jahren.",
    "description_fr": "Unlimitiertes Highspeed 5G Surfen und Telefonieren in der ganzen Schweiz unter 30 Jahren.",
    "description_it": "Unlimitiertes Highspeed 5G Surfen und Telefonieren in der ganzen Schweiz unter 30 Jahren.",
    "conditions_de": "Gültig für Jugendliche & Studierende in der Schweiz bis 30 Jahre.",
    "how_to_get_de": "1. Angebot auswählen\n2. Über den Link registrieren oder Legi vorweisen\n3. Rabatt sofort einlösen",
    "brand_id": "b-salt",
    "brand": {
      "id": "b-salt",
      "slug": "salt",
      "name": "Salt Mobile",
      "logo_url": null,
      "description_de": "Offizieller Partner Salt Mobile in der Schweiz",
      "website_url": "https://www.salt.ch",
      "categories": [
        "handy"
      ],
      "created_at": "2026-09-26T02:48:56.627Z",
      "updated_at": "2026-09-26T02:48:56.627Z"
    },
    "category_id": "cat-handy",
    "category": {
      "id": "cat-handy",
      "slug": "handy",
      "name_de": "Mobilfunk & Internet",
      "name_fr": "Mobilfunk & Internet",
      "name_it": "Mobilfunk & Internet",
      "icon": "📱",
      "description_de": "Angebote in Mobilfunk & Internet",
      "sort_order": 1,
      "created_at": "2026-09-26T02:48:56.627Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 59.95,
    "young_price": 24.95,
    "discount_percent": 58,
    "discount_amount": 35,
    "advantage_type": "reduced_price",
    "age_min": 16,
    "age_max": 30,
    "student_required": false,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.salt.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.627Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "RABATT",
      "SCHWEIZWEIT",
      "VERIFIZIERT"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": null,
    "checked_at": "2026-09-26T02:48:56.627Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 120,
    "click_count": 45,
    "created_at": "2026-09-26T02:48:56.627Z",
    "updated_at": "2026-09-26T02:48:56.627Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111112",
    "slug": "swisscom-blue-youth",
    "title_de": "Swisscom blue Mobile Youth 50% Rabatt",
    "title_fr": "Swisscom blue Mobile Youth 50% Rabatt",
    "title_it": "Swisscom blue Mobile Youth 50% Rabatt",
    "description_de": "Bestes Schweizer Mobilfunknetz mit 5G Speed und EU-Roaming zu reduzierten Jugendkonditionen.",
    "description_fr": "Bestes Schweizer Mobilfunknetz mit 5G Speed und EU-Roaming zu reduzierten Jugendkonditionen.",
    "description_it": "Bestes Schweizer Mobilfunknetz mit 5G Speed und EU-Roaming zu reduzierten Jugendkonditionen.",
    "conditions_de": "Gültig für Jugendliche & Studierende in der Schweiz bis 30 Jahre.",
    "how_to_get_de": "1. Angebot auswählen\n2. Über den Link registrieren oder Legi vorweisen\n3. Rabatt sofort einlösen",
    "brand_id": "b-swisscom",
    "brand": {
      "id": "b-swisscom",
      "slug": "swisscom",
      "name": "Swisscom",
      "logo_url": null,
      "description_de": "Offizieller Partner Swisscom in der Schweiz",
      "website_url": "https://www.swisscom.ch",
      "categories": [
        "handy"
      ],
      "created_at": "2026-09-26T02:48:56.627Z",
      "updated_at": "2026-09-26T02:48:56.627Z"
    },
    "category_id": "cat-handy",
    "category": {
      "id": "cat-handy",
      "slug": "handy",
      "name_de": "Mobilfunk & Internet",
      "name_fr": "Mobilfunk & Internet",
      "name_it": "Mobilfunk & Internet",
      "icon": "📱",
      "description_de": "Angebote in Mobilfunk & Internet",
      "sort_order": 1,
      "created_at": "2026-09-26T02:48:56.627Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 69.9,
    "young_price": 29.9,
    "discount_percent": 57,
    "discount_amount": 40.00000000000001,
    "advantage_type": "reduced_price",
    "age_min": 16,
    "age_max": 30,
    "student_required": false,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.swisscom.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.627Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "RABATT",
      "SCHWEIZWEIT",
      "VERIFIZIERT"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": null,
    "checked_at": "2026-09-26T02:48:56.627Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 120,
    "click_count": 45,
    "created_at": "2026-09-26T02:48:56.627Z",
    "updated_at": "2026-09-26T02:48:56.627Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111113",
    "slug": "projekt-neptun-laptops",
    "title_de": "Projekt Neptun: Bis 40% Rabatt auf MacBooks & ThinkPads",
    "title_fr": "Projekt Neptun: Bis 40% Rabatt auf MacBooks & ThinkPads",
    "title_it": "Projekt Neptun: Bis 40% Rabatt auf MacBooks & ThinkPads",
    "description_de": "Exklusive Verkaufsfenster an Schweizer Hochschulen für Laptops, Tablets und Monitore.",
    "description_fr": "Exklusive Verkaufsfenster an Schweizer Hochschulen für Laptops, Tablets und Monitore.",
    "description_it": "Exklusive Verkaufsfenster an Schweizer Hochschulen für Laptops, Tablets und Monitore.",
    "conditions_de": "Gültig für Jugendliche & Studierende in der Schweiz bis 30 Jahre.",
    "how_to_get_de": "1. Angebot auswählen\n2. Über den Link registrieren oder Legi vorweisen\n3. Rabatt sofort einlösen",
    "brand_id": "b-projekt-neptun",
    "brand": {
      "id": "b-projekt-neptun",
      "slug": "projekt-neptun",
      "name": "Projekt Neptun",
      "logo_url": null,
      "description_de": "Offizieller Partner Projekt Neptun in der Schweiz",
      "website_url": "https://www.projekt-neptun.ch",
      "categories": [
        "technik"
      ],
      "created_at": "2026-09-26T02:48:56.627Z",
      "updated_at": "2026-09-26T02:48:56.627Z"
    },
    "category_id": "cat-technik",
    "category": {
      "id": "cat-technik",
      "slug": "technik",
      "name_de": "Technik & Laptops",
      "name_fr": "Technik & Laptops",
      "name_it": "Technik & Laptops",
      "icon": "💻",
      "description_de": "Angebote in Technik & Laptops",
      "sort_order": 1,
      "created_at": "2026-09-26T02:48:56.627Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 1899,
    "young_price": 1199,
    "discount_percent": 37,
    "discount_amount": 700,
    "advantage_type": "reduced_price",
    "age_min": 16,
    "age_max": 30,
    "student_required": true,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.projekt-neptun.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.627Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "RABATT",
      "SCHWEIZWEIT",
      "VERIFIZIERT"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": null,
    "checked_at": "2026-09-26T02:48:56.627Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 120,
    "click_count": 45,
    "created_at": "2026-09-26T02:48:56.627Z",
    "updated_at": "2026-09-26T02:48:56.627Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111114",
    "slug": "apple-education-store",
    "title_de": "Apple Education Store: 10% Studentenrabatt auf Mac & iPad",
    "title_fr": "Apple Education Store: 10% Studentenrabatt auf Mac & iPad",
    "title_it": "Apple Education Store: 10% Studentenrabatt auf Mac & iPad",
    "description_de": "Dauerhafter Rabatt auf MacBooks, iPads und Zubehör mit gültiger Hochschul-Legi.",
    "description_fr": "Dauerhafter Rabatt auf MacBooks, iPads und Zubehör mit gültiger Hochschul-Legi.",
    "description_it": "Dauerhafter Rabatt auf MacBooks, iPads und Zubehör mit gültiger Hochschul-Legi.",
    "conditions_de": "Gültig für Jugendliche & Studierende in der Schweiz bis 30 Jahre.",
    "how_to_get_de": "1. Angebot auswählen\n2. Über den Link registrieren oder Legi vorweisen\n3. Rabatt sofort einlösen",
    "brand_id": "b-apple",
    "brand": {
      "id": "b-apple",
      "slug": "apple",
      "name": "Apple Store Switzerland",
      "logo_url": null,
      "description_de": "Offizieller Partner Apple Store Switzerland in der Schweiz",
      "website_url": "https://www.apple.ch",
      "categories": [
        "technik"
      ],
      "created_at": "2026-09-26T02:48:56.627Z",
      "updated_at": "2026-09-26T02:48:56.627Z"
    },
    "category_id": "cat-technik",
    "category": {
      "id": "cat-technik",
      "slug": "technik",
      "name_de": "Technik & Laptops",
      "name_fr": "Technik & Laptops",
      "name_it": "Technik & Laptops",
      "icon": "💻",
      "description_de": "Angebote in Technik & Laptops",
      "sort_order": 1,
      "created_at": "2026-09-26T02:48:56.627Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 1149,
    "young_price": 999,
    "discount_percent": 13,
    "discount_amount": 150,
    "advantage_type": "reduced_price",
    "age_min": 16,
    "age_max": 30,
    "student_required": true,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.apple.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.627Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "RABATT",
      "SCHWEIZWEIT",
      "VERIFIZIERT"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": null,
    "checked_at": "2026-09-26T02:48:56.627Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 120,
    "click_count": 45,
    "created_at": "2026-09-26T02:48:56.627Z",
    "updated_at": "2026-09-26T02:48:56.627Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111115",
    "slug": "spotify-student-discount",
    "title_de": "Spotify Premium Student für CHF 7.95 / Monat",
    "title_fr": "Spotify Premium Student für CHF 7.95 / Monat",
    "title_it": "Spotify Premium Student für CHF 7.95 / Monat",
    "description_de": "Unlimitiertes Musik-Streaming ohne Werbung zum halben Preis für immatrikulierte Studierende.",
    "description_fr": "Unlimitiertes Musik-Streaming ohne Werbung zum halben Preis für immatrikulierte Studierende.",
    "description_it": "Unlimitiertes Musik-Streaming ohne Werbung zum halben Preis für immatrikulierte Studierende.",
    "conditions_de": "Gültig für Jugendliche & Studierende in der Schweiz bis 30 Jahre.",
    "how_to_get_de": "1. Angebot auswählen\n2. Über den Link registrieren oder Legi vorweisen\n3. Rabatt sofort einlösen",
    "brand_id": "b-spotify",
    "brand": {
      "id": "b-spotify",
      "slug": "spotify",
      "name": "Spotify",
      "logo_url": null,
      "description_de": "Offizieller Partner Spotify in der Schweiz",
      "website_url": "https://www.spotify.ch",
      "categories": [
        "streaming"
      ],
      "created_at": "2026-09-26T02:48:56.627Z",
      "updated_at": "2026-09-26T02:48:56.627Z"
    },
    "category_id": "cat-streaming",
    "category": {
      "id": "cat-streaming",
      "slug": "streaming",
      "name_de": "Streaming & Musik",
      "name_fr": "Streaming & Musik",
      "name_it": "Streaming & Musik",
      "icon": "🎵",
      "description_de": "Angebote in Streaming & Musik",
      "sort_order": 1,
      "created_at": "2026-09-26T02:48:56.627Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 13.95,
    "young_price": 7.95,
    "discount_percent": 43,
    "discount_amount": 5.999999999999999,
    "advantage_type": "reduced_price",
    "age_min": 16,
    "age_max": 30,
    "student_required": true,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.spotify.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.627Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "RABATT",
      "SCHWEIZWEIT",
      "VERIFIZIERT"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": null,
    "checked_at": "2026-09-26T02:48:56.627Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 120,
    "click_count": 45,
    "created_at": "2026-09-26T02:48:56.627Z",
    "updated_at": "2026-09-26T02:48:56.627Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111116",
    "slug": "youtube-premium-student",
    "title_de": "YouTube Premium Student 45% Rabatt",
    "title_fr": "YouTube Premium Student 45% Rabatt",
    "title_it": "YouTube Premium Student 45% Rabatt",
    "description_de": "Werbefreie Videos, Hintergrunde Wiedergabe und YouTube Music Premium für Studierende.",
    "description_fr": "Werbefreie Videos, Hintergrunde Wiedergabe und YouTube Music Premium für Studierende.",
    "description_it": "Werbefreie Videos, Hintergrunde Wiedergabe und YouTube Music Premium für Studierende.",
    "conditions_de": "Gültig für Jugendliche & Studierende in der Schweiz bis 30 Jahre.",
    "how_to_get_de": "1. Angebot auswählen\n2. Über den Link registrieren oder Legi vorweisen\n3. Rabatt sofort einlösen",
    "brand_id": "b-youtube",
    "brand": {
      "id": "b-youtube",
      "slug": "youtube",
      "name": "YouTube CH",
      "logo_url": null,
      "description_de": "Offizieller Partner YouTube CH in der Schweiz",
      "website_url": "https://www.youtube.ch",
      "categories": [
        "streaming"
      ],
      "created_at": "2026-09-26T02:48:56.627Z",
      "updated_at": "2026-09-26T02:48:56.627Z"
    },
    "category_id": "cat-streaming",
    "category": {
      "id": "cat-streaming",
      "slug": "streaming",
      "name_de": "Streaming & Musik",
      "name_fr": "Streaming & Musik",
      "name_it": "Streaming & Musik",
      "icon": "🎵",
      "description_de": "Angebote in Streaming & Musik",
      "sort_order": 1,
      "created_at": "2026-09-26T02:48:56.627Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 15.9,
    "young_price": 7.9,
    "discount_percent": 50,
    "discount_amount": 8,
    "advantage_type": "reduced_price",
    "age_min": 16,
    "age_max": 30,
    "student_required": true,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.youtube.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.627Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "RABATT",
      "SCHWEIZWEIT",
      "VERIFIZIERT"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": null,
    "checked_at": "2026-09-26T02:48:56.627Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 120,
    "click_count": 45,
    "created_at": "2026-09-26T02:48:56.627Z",
    "updated_at": "2026-09-26T02:48:56.627Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111117",
    "slug": "zalando-studentenrabatt",
    "title_de": "Zalando: 10% Extra-Rabatt für Studierende",
    "title_fr": "Zalando: 10% Extra-Rabatt für Studierende",
    "title_it": "Zalando: 10% Extra-Rabatt für Studierende",
    "description_de": "Gutscheincode für Kleidung, Schuhe und Accessoires auf Zalando.ch.",
    "description_fr": "Gutscheincode für Kleidung, Schuhe und Accessoires auf Zalando.ch.",
    "description_it": "Gutscheincode für Kleidung, Schuhe und Accessoires auf Zalando.ch.",
    "conditions_de": "Gültig für Jugendliche & Studierende in der Schweiz bis 30 Jahre.",
    "how_to_get_de": "1. Angebot auswählen\n2. Über den Link registrieren oder Legi vorweisen\n3. Rabatt sofort einlösen",
    "brand_id": "b-zalando",
    "brand": {
      "id": "b-zalando",
      "slug": "zalando",
      "name": "Zalando Schweiz",
      "logo_url": null,
      "description_de": "Offizieller Partner Zalando Schweiz in der Schweiz",
      "website_url": "https://www.zalando.ch",
      "categories": [
        "mode"
      ],
      "created_at": "2026-09-26T02:48:56.627Z",
      "updated_at": "2026-09-26T02:48:56.627Z"
    },
    "category_id": "cat-mode",
    "category": {
      "id": "cat-mode",
      "slug": "mode",
      "name_de": "Mode & Style",
      "name_fr": "Mode & Style",
      "name_it": "Mode & Style",
      "icon": "👕",
      "description_de": "Angebote in Mode & Style",
      "sort_order": 1,
      "created_at": "2026-09-26T02:48:56.627Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 50,
    "young_price": 45,
    "discount_percent": 10,
    "discount_amount": 5,
    "advantage_type": "reduced_price",
    "age_min": 16,
    "age_max": 30,
    "student_required": true,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.zalando.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.627Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "RABATT",
      "SCHWEIZWEIT",
      "VERIFIZIERT"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": null,
    "checked_at": "2026-09-26T02:48:56.627Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 120,
    "click_count": 45,
    "created_at": "2026-09-26T02:48:56.627Z",
    "updated_at": "2026-09-26T02:48:56.627Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111118",
    "slug": "nike-student-discount",
    "title_de": "Nike: 10% Studentenrabatt auf Sneaker & Wear",
    "title_fr": "Nike: 10% Studentenrabatt auf Sneaker & Wear",
    "title_it": "Nike: 10% Studentenrabatt auf Sneaker & Wear",
    "description_de": "Exklusiver Rabattcode für den offiziellen Nike Online Store.",
    "description_fr": "Exklusiver Rabattcode für den offiziellen Nike Online Store.",
    "description_it": "Exklusiver Rabattcode für den offiziellen Nike Online Store.",
    "conditions_de": "Gültig für Jugendliche & Studierende in der Schweiz bis 30 Jahre.",
    "how_to_get_de": "1. Angebot auswählen\n2. Über den Link registrieren oder Legi vorweisen\n3. Rabatt sofort einlösen",
    "brand_id": "b-nike",
    "brand": {
      "id": "b-nike",
      "slug": "nike",
      "name": "Nike CH",
      "logo_url": null,
      "description_de": "Offizieller Partner Nike CH in der Schweiz",
      "website_url": "https://www.nike.ch",
      "categories": [
        "mode"
      ],
      "created_at": "2026-09-26T02:48:56.627Z",
      "updated_at": "2026-09-26T02:48:56.627Z"
    },
    "category_id": "cat-mode",
    "category": {
      "id": "cat-mode",
      "slug": "mode",
      "name_de": "Mode & Style",
      "name_fr": "Mode & Style",
      "name_it": "Mode & Style",
      "icon": "👕",
      "description_de": "Angebote in Mode & Style",
      "sort_order": 1,
      "created_at": "2026-09-26T02:48:56.627Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 100,
    "young_price": 90,
    "discount_percent": 10,
    "discount_amount": 10,
    "advantage_type": "reduced_price",
    "age_min": 16,
    "age_max": 30,
    "student_required": true,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.nike.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.627Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "RABATT",
      "SCHWEIZWEIT",
      "VERIFIZIERT"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": null,
    "checked_at": "2026-09-26T02:48:56.627Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 120,
    "click_count": 45,
    "created_at": "2026-09-26T02:48:56.627Z",
    "updated_at": "2026-09-26T02:48:56.627Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111119",
    "slug": "asvz-sport-mitgliedschaft",
    "title_de": "ASVZ Hochschulsport Zürich: Gratis im Semesterbeitrag",
    "title_fr": "ASVZ Hochschulsport Zürich: Gratis im Semesterbeitrag",
    "title_it": "ASVZ Hochschulsport Zürich: Gratis im Semesterbeitrag",
    "description_de": "Zugang zu 5 modernen Sport Centern, Saunen und über 120 Sportarten in Zürich.",
    "description_fr": "Zugang zu 5 modernen Sport Centern, Saunen und über 120 Sportarten in Zürich.",
    "description_it": "Zugang zu 5 modernen Sport Centern, Saunen und über 120 Sportarten in Zürich.",
    "conditions_de": "Gültig für Jugendliche & Studierende in der Schweiz bis 30 Jahre.",
    "how_to_get_de": "1. Angebot auswählen\n2. Über den Link registrieren oder Legi vorweisen\n3. Rabatt sofort einlösen",
    "brand_id": "b-asvz",
    "brand": {
      "id": "b-asvz",
      "slug": "asvz",
      "name": "ASVZ Akademischer Sportverband Zürich",
      "logo_url": null,
      "description_de": "Offizieller Partner ASVZ Akademischer Sportverband Zürich in der Schweiz",
      "website_url": "https://www.asvz.ch",
      "categories": [
        "fitness"
      ],
      "created_at": "2026-09-26T02:48:56.627Z",
      "updated_at": "2026-09-26T02:48:56.627Z"
    },
    "category_id": "cat-fitness",
    "category": {
      "id": "cat-fitness",
      "slug": "fitness",
      "name_de": "Fitness & Bergsport",
      "name_fr": "Fitness & Bergsport",
      "name_it": "Fitness & Bergsport",
      "icon": "🏋️",
      "description_de": "Angebote in Fitness & Bergsport",
      "sort_order": 1,
      "created_at": "2026-09-26T02:48:56.627Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 800,
    "young_price": 0,
    "discount_percent": 100,
    "discount_amount": 800,
    "advantage_type": "free",
    "age_min": 16,
    "age_max": 30,
    "student_required": true,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.asvz.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.627Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "KOSTENLOS",
      "SCHWEIZWEIT",
      "VERIFIZIERT"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": null,
    "checked_at": "2026-09-26T02:48:56.627Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 120,
    "click_count": 45,
    "created_at": "2026-09-26T02:48:56.627Z",
    "updated_at": "2026-09-26T02:48:56.627Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111120",
    "slug": "unisport-bern-access",
    "title_de": "UNISPORT Bern: Komplettes Sportangebot für UniBE & BFH",
    "title_fr": "UNISPORT Bern: Komplettes Sportangebot für UniBE & BFH",
    "title_it": "UNISPORT Bern: Komplettes Sportangebot für UniBE & BFH",
    "description_de": "Mehr als 100 Sportarten, Kletterwände und Outdoor-Kurse für Studierende in Bern.",
    "description_fr": "Mehr als 100 Sportarten, Kletterwände und Outdoor-Kurse für Studierende in Bern.",
    "description_it": "Mehr als 100 Sportarten, Kletterwände und Outdoor-Kurse für Studierende in Bern.",
    "conditions_de": "Gültig für Jugendliche & Studierende in der Schweiz bis 30 Jahre.",
    "how_to_get_de": "1. Angebot auswählen\n2. Über den Link registrieren oder Legi vorweisen\n3. Rabatt sofort einlösen",
    "brand_id": "b-unisport",
    "brand": {
      "id": "b-unisport",
      "slug": "unisport",
      "name": "UNISPORT Bern",
      "logo_url": null,
      "description_de": "Offizieller Partner UNISPORT Bern in der Schweiz",
      "website_url": "https://www.unisport.ch",
      "categories": [
        "fitness"
      ],
      "created_at": "2026-09-26T02:48:56.627Z",
      "updated_at": "2026-09-26T02:48:56.627Z"
    },
    "category_id": "cat-fitness",
    "category": {
      "id": "cat-fitness",
      "slug": "fitness",
      "name_de": "Fitness & Bergsport",
      "name_fr": "Fitness & Bergsport",
      "name_it": "Fitness & Bergsport",
      "icon": "🏋️",
      "description_de": "Angebote in Fitness & Bergsport",
      "sort_order": 1,
      "created_at": "2026-09-26T02:48:56.627Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 750,
    "young_price": 0,
    "discount_percent": 100,
    "discount_amount": 750,
    "advantage_type": "free",
    "age_min": 16,
    "age_max": 30,
    "student_required": true,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.unisport.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.627Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "KOSTENLOS",
      "SCHWEIZWEIT",
      "VERIFIZIERT"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": null,
    "checked_at": "2026-09-26T02:48:56.627Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 120,
    "click_count": 45,
    "created_at": "2026-09-26T02:48:56.627Z",
    "updated_at": "2026-09-26T02:48:56.627Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111121",
    "slug": "pathe-kino-student",
    "title_de": "Pathé & Blue Cinema Kinomontag: Tickets für CHF 14.–",
    "title_fr": "Pathé & Blue Cinema Kinomontag: Tickets für CHF 14.–",
    "title_it": "Pathé & Blue Cinema Kinomontag: Tickets für CHF 14.–",
    "description_de": "Vergünstigte Kinotickets jeden Montag in allen Schweizer Pathé und Blue Cinema Kinos gegen Vorzeigen der Legi.",
    "description_fr": "Vergünstigte Kinotickets jeden Montag in allen Schweizer Pathé und Blue Cinema Kinos gegen Vorzeigen der Legi.",
    "description_it": "Vergünstigte Kinotickets jeden Montag in allen Schweizer Pathé und Blue Cinema Kinos gegen Vorzeigen der Legi.",
    "conditions_de": "Gültig für Jugendliche & Studierende in der Schweiz bis 30 Jahre.",
    "how_to_get_de": "1. Angebot auswählen\n2. Über den Link registrieren oder Legi vorweisen\n3. Rabatt sofort einlösen",
    "brand_id": "b-pathe",
    "brand": {
      "id": "b-pathe",
      "slug": "pathe",
      "name": "Pathé Kinos Schweiz",
      "logo_url": null,
      "description_de": "Offizieller Partner Pathé Kinos Schweiz in der Schweiz",
      "website_url": "https://www.pathe.ch",
      "categories": [
        "kino"
      ],
      "created_at": "2026-09-26T02:48:56.627Z",
      "updated_at": "2026-09-26T02:48:56.627Z"
    },
    "category_id": "cat-kino",
    "category": {
      "id": "cat-kino",
      "slug": "kino",
      "name_de": "Kino & Ausgang",
      "name_fr": "Kino & Ausgang",
      "name_it": "Kino & Ausgang",
      "icon": "🎬",
      "description_de": "Angebote in Kino & Ausgang",
      "sort_order": 1,
      "created_at": "2026-09-26T02:48:56.628Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 22,
    "young_price": 14,
    "discount_percent": 36,
    "discount_amount": 8,
    "advantage_type": "reduced_price",
    "age_min": 16,
    "age_max": 30,
    "student_required": true,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.pathe.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.628Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "RABATT",
      "SCHWEIZWEIT",
      "VERIFIZIERT"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": null,
    "checked_at": "2026-09-26T02:48:56.628Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 120,
    "click_count": 45,
    "created_at": "2026-09-26T02:48:56.628Z",
    "updated_at": "2026-09-26T02:48:56.628Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111122",
    "slug": "too-good-to-go-food",
    "title_de": "Too Good To Go: Essen retten ab CHF 4.90",
    "title_fr": "Too Good To Go: Essen retten ab CHF 4.90",
    "title_it": "Too Good To Go: Essen retten ab CHF 4.90",
    "description_de": "Ueber-Schuss-Gerichte aus Schweizer Bäckereien und Restaurants zum Drittel des Preises retten.",
    "description_fr": "Ueber-Schuss-Gerichte aus Schweizer Bäckereien und Restaurants zum Drittel des Preises retten.",
    "description_it": "Ueber-Schuss-Gerichte aus Schweizer Bäckereien und Restaurants zum Drittel des Preises retten.",
    "conditions_de": "Gültig für Jugendliche & Studierende in der Schweiz bis 30 Jahre.",
    "how_to_get_de": "1. Angebot auswählen\n2. Über den Link registrieren oder Legi vorweisen\n3. Rabatt sofort einlösen",
    "brand_id": "b-too-good-to-go",
    "brand": {
      "id": "b-too-good-to-go",
      "slug": "too-good-to-go",
      "name": "Too Good To Go CH",
      "logo_url": null,
      "description_de": "Offizieller Partner Too Good To Go CH in der Schweiz",
      "website_url": "https://www.too-good-to-go.ch",
      "categories": [
        "restaurants"
      ],
      "created_at": "2026-09-26T02:48:56.628Z",
      "updated_at": "2026-09-26T02:48:56.628Z"
    },
    "category_id": "cat-restaurants",
    "category": {
      "id": "cat-restaurants",
      "slug": "restaurants",
      "name_de": "Essen & Mensa",
      "name_fr": "Essen & Mensa",
      "name_it": "Essen & Mensa",
      "icon": "🍔",
      "description_de": "Angebote in Essen & Mensa",
      "sort_order": 1,
      "created_at": "2026-09-26T02:48:56.628Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 15,
    "young_price": 4.9,
    "discount_percent": 67,
    "discount_amount": 10.1,
    "advantage_type": "reduced_price",
    "age_min": 16,
    "age_max": 30,
    "student_required": false,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.too-good-to-go.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.628Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "RABATT",
      "SCHWEIZWEIT",
      "VERIFIZIERT"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": null,
    "checked_at": "2026-09-26T02:48:56.628Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 120,
    "click_count": 45,
    "created_at": "2026-09-26T02:48:56.628Z",
    "updated_at": "2026-09-26T02:48:56.628Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111123",
    "slug": "eth-uzh-mensa-deus",
    "title_de": "ETH & UZH Mensen: Tagesmenüs ab CHF 6.90",
    "title_fr": "ETH & UZH Mensen: Tagesmenüs ab CHF 6.90",
    "title_it": "ETH & UZH Mensen: Tagesmenüs ab CHF 6.90",
    "description_de": "Frische, ausgewogene Mittagsmenüs und vegetarische Buffets an den Schweizer Hochschulen.",
    "description_fr": "Frische, ausgewogene Mittagsmenüs und vegetarische Buffets an den Schweizer Hochschulen.",
    "description_it": "Frische, ausgewogene Mittagsmenüs und vegetarische Buffets an den Schweizer Hochschulen.",
    "conditions_de": "Gültig für Jugendliche & Studierende in der Schweiz bis 30 Jahre.",
    "how_to_get_de": "1. Angebot auswählen\n2. Über den Link registrieren oder Legi vorweisen\n3. Rabatt sofort einlösen",
    "brand_id": "b-eth-mensa",
    "brand": {
      "id": "b-eth-mensa",
      "slug": "eth-mensa",
      "name": "SV Group Mensen",
      "logo_url": null,
      "description_de": "Offizieller Partner SV Group Mensen in der Schweiz",
      "website_url": "https://www.eth-mensa.ch",
      "categories": [
        "restaurants"
      ],
      "created_at": "2026-09-26T02:48:56.628Z",
      "updated_at": "2026-09-26T02:48:56.628Z"
    },
    "category_id": "cat-restaurants",
    "category": {
      "id": "cat-restaurants",
      "slug": "restaurants",
      "name_de": "Essen & Mensa",
      "name_fr": "Essen & Mensa",
      "name_it": "Essen & Mensa",
      "icon": "🍔",
      "description_de": "Angebote in Essen & Mensa",
      "sort_order": 1,
      "created_at": "2026-09-26T02:48:56.628Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 16.5,
    "young_price": 6.9,
    "discount_percent": 58,
    "discount_amount": 9.6,
    "advantage_type": "reduced_price",
    "age_min": 16,
    "age_max": 30,
    "student_required": true,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.eth-mensa.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.628Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "RABATT",
      "SCHWEIZWEIT",
      "VERIFIZIERT"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": null,
    "checked_at": "2026-09-26T02:48:56.628Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 120,
    "click_count": 45,
    "created_at": "2026-09-26T02:48:56.628Z",
    "updated_at": "2026-09-26T02:48:56.628Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111124",
    "slug": "swisscovery-library",
    "title_de": "Swisscovery Bibliotheksnetz: 100% Kostenloser Zugang",
    "title_fr": "Swisscovery Bibliotheksnetz: 100% Kostenloser Zugang",
    "title_it": "Swisscovery Bibliotheksnetz: 100% Kostenloser Zugang",
    "description_de": "Millionen wissenschaftliche Bücher, Artikel und E-Books aller Schweizer Hochschulbibliotheken über Switch edu-ID.",
    "description_fr": "Millionen wissenschaftliche Bücher, Artikel und E-Books aller Schweizer Hochschulbibliotheken über Switch edu-ID.",
    "description_it": "Millionen wissenschaftliche Bücher, Artikel und E-Books aller Schweizer Hochschulbibliotheken über Switch edu-ID.",
    "conditions_de": "Gültig für Jugendliche & Studierende in der Schweiz bis 30 Jahre.",
    "how_to_get_de": "1. Angebot auswählen\n2. Über den Link registrieren oder Legi vorweisen\n3. Rabatt sofort einlösen",
    "brand_id": "b-swisscovery",
    "brand": {
      "id": "b-swisscovery",
      "slug": "swisscovery",
      "name": "SLSP Swisscovery",
      "logo_url": null,
      "description_de": "Offizieller Partner SLSP Swisscovery in der Schweiz",
      "website_url": "https://www.swisscovery.ch",
      "categories": [
        "bildung"
      ],
      "created_at": "2026-09-26T02:48:56.628Z",
      "updated_at": "2026-09-26T02:48:56.628Z"
    },
    "category_id": "cat-bildung",
    "category": {
      "id": "cat-bildung",
      "slug": "bildung",
      "name_de": "Studium & Campus",
      "name_fr": "Studium & Campus",
      "name_it": "Studium & Campus",
      "icon": "🎓",
      "description_de": "Angebote in Studium & Campus",
      "sort_order": 1,
      "created_at": "2026-09-26T02:48:56.628Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 100,
    "young_price": 0,
    "discount_percent": 100,
    "discount_amount": 100,
    "advantage_type": "free",
    "age_min": 16,
    "age_max": 30,
    "student_required": true,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.swisscovery.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.628Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "KOSTENLOS",
      "SCHWEIZWEIT",
      "VERIFIZIERT"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": null,
    "checked_at": "2026-09-26T02:48:56.628Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 120,
    "click_count": 45,
    "created_at": "2026-09-26T02:48:56.628Z",
    "updated_at": "2026-09-26T02:48:56.628Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111125",
    "slug": "kulturlegi-caritas",
    "title_de": "Caritas KulturLegi: Bis zu 70% Rabatt auf Kultur & Sport",
    "title_fr": "Caritas KulturLegi: Bis zu 70% Rabatt auf Kultur & Sport",
    "title_it": "Caritas KulturLegi: Bis zu 70% Rabatt auf Kultur & Sport",
    "description_de": "Vergünstigter Zugang zu Museen, Theatern, Konzerten und Sportstätten für schmale Budgets.",
    "description_fr": "Vergünstigter Zugang zu Museen, Theatern, Konzerten und Sportstätten für schmale Budgets.",
    "description_it": "Vergünstigter Zugang zu Museen, Theatern, Konzerten und Sportstätten für schmale Budgets.",
    "conditions_de": "Gültig für Jugendliche & Studierende in der Schweiz bis 30 Jahre.",
    "how_to_get_de": "1. Angebot auswählen\n2. Über den Link registrieren oder Legi vorweisen\n3. Rabatt sofort einlösen",
    "brand_id": "b-caritas",
    "brand": {
      "id": "b-caritas",
      "slug": "caritas",
      "name": "Caritas Schweiz",
      "logo_url": null,
      "description_de": "Offizieller Partner Caritas Schweiz in der Schweiz",
      "website_url": "https://www.caritas.ch",
      "categories": [
        "events"
      ],
      "created_at": "2026-09-26T02:48:56.628Z",
      "updated_at": "2026-09-26T02:48:56.628Z"
    },
    "category_id": "cat-events",
    "category": {
      "id": "cat-events",
      "slug": "events",
      "name_de": "Kultur & Festivals",
      "name_fr": "Kultur & Festivals",
      "name_it": "Kultur & Festivals",
      "icon": "🎟️",
      "description_de": "Angebote in Kultur & Festivals",
      "sort_order": 1,
      "created_at": "2026-09-26T02:48:56.628Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 100,
    "young_price": 10,
    "discount_percent": 90,
    "discount_amount": 90,
    "advantage_type": "reduced_price",
    "age_min": 16,
    "age_max": 30,
    "student_required": false,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.caritas.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.628Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "RABATT",
      "SCHWEIZWEIT",
      "VERIFIZIERT"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": null,
    "checked_at": "2026-09-26T02:48:56.628Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 120,
    "click_count": 45,
    "created_at": "2026-09-26T02:48:56.628Z",
    "updated_at": "2026-09-26T02:48:56.628Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111126",
    "slug": "museumspass-ch",
    "title_de": "Schweizer Museumspass: Freier Eintritt in 500+ Museen",
    "title_fr": "Schweizer Museumspass: Freier Eintritt in 500+ Museen",
    "title_it": "Schweizer Museumspass: Freier Eintritt in 500+ Museen",
    "description_de": "Kostenloser Zutritt zu Schlössern, Kunstmuseen und Ausstellungen in der ganzen Schweiz.",
    "description_fr": "Kostenloser Zutritt zu Schlössern, Kunstmuseen und Ausstellungen in der ganzen Schweiz.",
    "description_it": "Kostenloser Zutritt zu Schlössern, Kunstmuseen und Ausstellungen in der ganzen Schweiz.",
    "conditions_de": "Gültig für Jugendliche & Studierende in der Schweiz bis 30 Jahre.",
    "how_to_get_de": "1. Angebot auswählen\n2. Über den Link registrieren oder Legi vorweisen\n3. Rabatt sofort einlösen",
    "brand_id": "b-museumspass",
    "brand": {
      "id": "b-museumspass",
      "slug": "museumspass",
      "name": "Schweizer Museumspass",
      "logo_url": null,
      "description_de": "Offizieller Partner Schweizer Museumspass in der Schweiz",
      "website_url": "https://www.museumspass.ch",
      "categories": [
        "events"
      ],
      "created_at": "2026-09-26T02:48:56.628Z",
      "updated_at": "2026-09-26T02:48:56.628Z"
    },
    "category_id": "cat-events",
    "category": {
      "id": "cat-events",
      "slug": "events",
      "name_de": "Kultur & Festivals",
      "name_fr": "Kultur & Festivals",
      "name_it": "Kultur & Festivals",
      "icon": "🎟️",
      "description_de": "Angebote in Kultur & Festivals",
      "sort_order": 1,
      "created_at": "2026-09-26T02:48:56.628Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 177,
    "young_price": 120,
    "discount_percent": 32,
    "discount_amount": 57,
    "advantage_type": "reduced_price",
    "age_min": 16,
    "age_max": 30,
    "student_required": false,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.museumspass.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.628Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "RABATT",
      "SCHWEIZWEIT",
      "VERIFIZIERT"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": null,
    "checked_at": "2026-09-26T02:48:56.628Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 120,
    "click_count": 45,
    "created_at": "2026-09-26T02:48:56.628Z",
    "updated_at": "2026-09-26T02:48:56.628Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111127",
    "slug": "xbox-game-pass-ch",
    "title_de": "Xbox Game Pass PC: CHF 1.– im ersten Monat",
    "title_fr": "Xbox Game Pass PC: CHF 1.– im ersten Monat",
    "title_it": "Xbox Game Pass PC: CHF 1.– im ersten Monat",
    "description_de": "Zugriff auf hunderte PC-Spiele inklusive Neuerscheinungen an Tag 1.",
    "description_fr": "Zugriff auf hunderte PC-Spiele inklusive Neuerscheinungen an Tag 1.",
    "description_it": "Zugriff auf hunderte PC-Spiele inklusive Neuerscheinungen an Tag 1.",
    "conditions_de": "Gültig für Jugendliche & Studierende in der Schweiz bis 30 Jahre.",
    "how_to_get_de": "1. Angebot auswählen\n2. Über den Link registrieren oder Legi vorweisen\n3. Rabatt sofort einlösen",
    "brand_id": "b-microsoft",
    "brand": {
      "id": "b-microsoft",
      "slug": "microsoft",
      "name": "Microsoft Gaming",
      "logo_url": null,
      "description_de": "Offizieller Partner Microsoft Gaming in der Schweiz",
      "website_url": "https://www.microsoft.ch",
      "categories": [
        "gaming"
      ],
      "created_at": "2026-09-26T02:48:56.628Z",
      "updated_at": "2026-09-26T02:48:56.628Z"
    },
    "category_id": "cat-gaming",
    "category": {
      "id": "cat-gaming",
      "slug": "gaming",
      "name_de": "Gaming & Esport",
      "name_fr": "Gaming & Esport",
      "name_it": "Gaming & Esport",
      "icon": "🎮",
      "description_de": "Angebote in Gaming & Esport",
      "sort_order": 1,
      "created_at": "2026-09-26T02:48:56.628Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 12.99,
    "young_price": 1,
    "discount_percent": 92,
    "discount_amount": 11.99,
    "advantage_type": "reduced_price",
    "age_min": 16,
    "age_max": 30,
    "student_required": false,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.microsoft.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.628Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "RABATT",
      "SCHWEIZWEIT",
      "VERIFIZIERT"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": null,
    "checked_at": "2026-09-26T02:48:56.628Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 120,
    "click_count": 45,
    "created_at": "2026-09-26T02:48:56.628Z",
    "updated_at": "2026-09-26T02:48:56.628Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111128",
    "slug": "neon-free-card-gratis",
    "title_de": "Gratis Neon Mastercard & Willkommens-Bonus",
    "title_fr": "Gratis Neon Mastercard & Willkommens-Bonus",
    "title_it": "Gratis Neon Mastercard & Willkommens-Bonus",
    "description_de": "Eröffne dein Schweizer Konto kostenlos und erhalte die Debitkarte ohne Versandkosten.",
    "description_fr": "Eröffne dein Schweizer Konto kostenlos und erhalte die Debitkarte ohne Versandkosten.",
    "description_it": "Eröffne dein Schweizer Konto kostenlos und erhalte die Debitkarte ohne Versandkosten.",
    "conditions_de": "Gültig für Jugendliche & Studierende in der Schweiz bis 30 Jahre.",
    "how_to_get_de": "1. Angebot auswählen\n2. Über den Link registrieren oder Legi vorweisen\n3. Rabatt sofort einlösen",
    "brand_id": "b-neon",
    "brand": {
      "id": "b-neon",
      "slug": "neon",
      "name": "Neon Bank",
      "logo_url": null,
      "description_de": "Offizieller Partner Neon Bank in der Schweiz",
      "website_url": "https://www.neon.ch",
      "categories": [
        "gratis"
      ],
      "created_at": "2026-09-26T02:48:56.628Z",
      "updated_at": "2026-09-26T02:48:56.628Z"
    },
    "category_id": "cat-gratis",
    "category": {
      "id": "cat-gratis",
      "slug": "gratis",
      "name_de": "Kostenlos & Freebies",
      "name_fr": "Kostenlos & Freebies",
      "name_it": "Kostenlos & Freebies",
      "icon": "🆓",
      "description_de": "Angebote in Kostenlos & Freebies",
      "sort_order": 1,
      "created_at": "2026-09-26T02:48:56.628Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 50,
    "young_price": 0,
    "discount_percent": 100,
    "discount_amount": 50,
    "advantage_type": "free",
    "age_min": 16,
    "age_max": 30,
    "student_required": false,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.neon.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.628Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "KOSTENLOS",
      "SCHWEIZWEIT",
      "VERIFIZIERT"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": null,
    "checked_at": "2026-09-26T02:48:56.628Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 120,
    "click_count": 45,
    "created_at": "2026-09-26T02:48:56.628Z",
    "updated_at": "2026-09-26T02:48:56.628Z"
  }
];

export async function getOffers(filters?: OfferFilters, page = 1, limit = 20): Promise<PaginatedOffers> {
  let filtered = [...FALLBACK_OFFERS];

  if (filters?.category_slug) {
    filtered = filtered.filter((o) => o.category?.slug === filters.category_slug);
  }
  if (filters?.city_slug) {
    filtered = filtered.filter((o) => o.is_nationwide || o.city?.slug === filters.city_slug);
  }
  if (filters?.brand_slug) {
    filtered = filtered.filter((o) => o.brand?.slug === filters.brand_slug);
  }
  if (filters?.advantage_type) {
    filtered = filtered.filter((o) => o.advantage_type === filters.advantage_type);
  }
  if (filters?.search) {
    const q = filters.search.toLowerCase();
    filtered = filtered.filter(
      (o) =>
        o.title_de.toLowerCase().includes(q) ||
        (o.description_de && o.description_de.toLowerCase().includes(q)) ||
        (o.brand && o.brand.name.toLowerCase().includes(q))
    );
  }

  const startIndex = (page - 1) * limit;
  const paginated = filtered.slice(startIndex, startIndex + limit);

  if (!isSupabaseConfigured()) {
    return {
      offers: paginated,
      total: filtered.length,
      page,
      limit,
      hasMore: startIndex + limit < filtered.length,
      total_pages: Math.ceil(filtered.length / limit),
    };
  }

  try {
    const supabase = await createClient();
    let query = supabase.from("offers").select("*, brand:brands(*), category:categories(*), city:cities(*)", { count: "exact" }).eq("status", "published");

    if (filters?.category_slug) {
      const { data: cat } = await supabase.from("categories").select("id").eq("slug", filters.category_slug).single();
      if (cat) query = query.eq("category_id", cat.id);
    }
    if (filters?.brand_slug) {
      const { data: br } = await supabase.from("brands").select("id").eq("slug", filters.brand_slug).single();
      if (br) query = query.eq("brand_id", br.id);
    }

    const { data, count, error } = await Promise.race([
      query.range(startIndex, startIndex + limit - 1),
      new Promise<{ data: null; count: null; error: Error }>((_, reject) => setTimeout(() => reject(new Error("Timeout")), 1000))
    ]);

    if (!error && data && data.length > 0) {
      const tot = count || data.length;
      return {
        offers: data as Offer[],
        total: tot,
        page,
        limit,
        hasMore: startIndex + limit < tot,
        total_pages: Math.ceil(tot / limit),
      };
    }
  } catch {}

  return {
    offers: paginated,
    total: filtered.length,
    page,
    limit,
    hasMore: startIndex + limit < filtered.length,
    total_pages: Math.ceil(filtered.length / limit),
  };
}

export async function getOfferBySlug(slug: string): Promise<Offer | null> {
  const normSlug = slug.toLowerCase().trim();
  const fallback = FALLBACK_OFFERS.find(
    (o) => o.slug.toLowerCase() === normSlug || o.id === slug
  ) || null;

  if (!isSupabaseConfigured()) return fallback;

  try {
    const supabase = await createClient();
    const { data } = await fetchWithTimeout(
      supabase
        .from("offers")
        .select("*, brand:brands(*), category:categories(*), city:cities(*)")
        .eq("slug", normSlug)
        .maybeSingle(),
      5000
    ).catch(() => ({ data: null }));

    if (data) return data as Offer;
  } catch (e) {
    console.error("getOfferBySlug error:", e);
  }

  return fallback;
}

export async function getTopOffers(limit = 6, page = 1): Promise<Offer[]> {
  const res = await getOffers(undefined, page, limit);
  return res.offers;
}

export async function getVerifiedStudentOffers(limit = 24, page = 1): Promise<Offer[]> {
  const all = await getOffers({ student: true, limit: 100 }).catch(() => ({ offers: [] }));
  const pool = all.offers && all.offers.length > 0 ? all.offers : FALLBACK_OFFERS;
  const filtered = pool.filter((o) => o.student_required || o.tags?.includes("STUDENTEN"));
  const res = filtered.length > 0 ? filtered : pool;
  return res.slice((page - 1) * limit, page * limit);
}

export async function getVerifiedUnderAgeOffers(maxAge = 30, limit = 24, page = 1): Promise<Offer[]> {
  const all = await getOffers({ limit: 100 }).catch(() => ({ offers: [] }));
  const pool = all.offers && all.offers.length > 0 ? all.offers : FALLBACK_OFFERS;
  const filtered = pool.filter((o) => !o.age_max || o.age_max <= maxAge);
  return filtered.slice((page - 1) * limit, page * limit);
}

export async function getVerifiedFreeOffers(limit = 24, page = 1): Promise<Offer[]> {
  const all = await getOffers({ advantage_type: "free", limit: 100 }).catch(() => ({ offers: [] }));
  const pool = all.offers && all.offers.length > 0 ? all.offers : FALLBACK_OFFERS;
  const filtered = pool.filter((o) => o.advantage_type === "free" || o.young_price === 0 || o.tags?.includes("KOSTENLOS"));
  const res = filtered.length > 0 ? filtered : pool;
  return res.slice((page - 1) * limit, page * limit);
}

export const getStudentOffers = getVerifiedStudentOffers;
export const getUnder25Offers = (limit = 24, page = 1) => getVerifiedUnderAgeOffers(25, limit, page);
export const getFreeOffers = getVerifiedFreeOffers;

export const getVerifiedOffers = getOffers;
export const getPublishedOffers = getOffers;
export const getVerifiedTopOffers = getTopOffers;
export const getVerifiedNewOffers = getTopOffers;
export const getVerifiedExpiringOffers = getTopOffers;
export const getVorteilDerWoche = async (...args: any[]) => FALLBACK_OFFERS[0];
export const getDemoOffers = async (...args: any[]) => FALLBACK_OFFERS;
export const incrementOfferView = async (...args: any[]) => {};

export async function searchOffers(query: string, limit = 10): Promise<Offer[]> {
  const q = query.toLowerCase();
  return FALLBACK_OFFERS.filter(o => o.title_de.toLowerCase().includes(q) || (o.description_de && o.description_de.toLowerCase().includes(q))).slice(0, limit);
}

export async function getSimilarOffers(offerId: string, limit = 4): Promise<Offer[]> {
  return FALLBACK_OFFERS.filter(o => o.id !== offerId).slice(0, limit);
}

export async function getOffersByCategory(categorySlug: string, limit = 12): Promise<Offer[]> {
  return FALLBACK_OFFERS.filter(o => o.category?.slug === categorySlug).slice(0, limit);
}

export async function getOffersByCity(citySlug: string, limit = 12): Promise<Offer[]> {
  return FALLBACK_OFFERS.filter(o => o.city?.slug === citySlug || o.is_nationwide).slice(0, limit);
}

export async function getOffersByBrand(brandSlug: string, limit = 12): Promise<Offer[]> {
  return FALLBACK_OFFERS.filter(o => o.brand?.slug === brandSlug).slice(0, limit);
}
