// services/offers.ts
import { Offer, OfferFilters, PaginatedOffers } from "@/types";
import { fetchWithTimeout } from "@/lib/fetchWithTimeout";
import { createClient, isSupabaseConfigured } from "@/lib/supabase/server";

export const FALLBACK_OFFERS: Offer[] = [
  {
    "id": "b1111111-1111-4111-a111-111111111101",
    "slug": "sbb-ga-night",
    "title_de": "SBB GA Night: \u00d6V-Fahrt ab 19:00 Uhr f\u00fcr CHF 99.\u2013 pro Jahr",
    "title_fr": "SBB GA Night: \u00d6V-Fahrt ab 19:00 Uhr f\u00fcr CHF 99.\u2013 pro Jahr",
    "title_it": "SBB GA Night: \u00d6V-Fahrt ab 19:00 Uhr f\u00fcr CHF 99.\u2013 pro Jahr",
    "description_de": "Freie Fahrt im gesamten Schweizer \u00d6V-Netz ab 19:00 Uhr f\u00fcr Jugendliche unter 25 Jahren.",
    "description_fr": "Freie Fahrt im gesamten Schweizer \u00d6V-Netz ab 19:00 Uhr f\u00fcr Jugendliche unter 25 Jahren.",
    "description_it": "Freie Fahrt im gesamten Schweizer \u00d6V-Netz ab 19:00 Uhr f\u00fcr Jugendliche unter 25 Jahren.",
    "conditions_de": "G\u00fcltig f\u00fcr Jugendliche von 16 bis 25 Jahren mit g\u00fcltigem Swisspass.",
    "how_to_get_de": "1. Swisspass-Konto erstellen\n2. Identit\u00e4t verifizieren\n3. GA Night online oder am Schalter f\u00fcr CHF 99.\u2013 kaufen",
    "brand_id": "b-sbb",
    "brand": {
      "id": "b-sbb",
      "slug": "sbb",
      "name": "SBB CFF FFS",
      "logo_url": null,
      "description_de": "Der f\u00fchrende Schweizer \u00d6V-Anbieter mit speziellen Tarifen f\u00fcr Jugendliche und Studierende.",
      "website_url": "https://www.sbb.ch",
      "categories": [
        "reisen"
      ],
      "created_at": "2026-09-26T02:48:56.626Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-reisen",
    "category": {
      "id": "cat-reisen",
      "slug": "reisen",
      "name_de": "Reisen & \u00d6V",
      "name_fr": "Reisen & \u00d6V",
      "name_it": "Reisen & \u00d6V",
      "icon": "\ud83d\ude86",
      "description_de": "Angebote in Reisen & \u00d6V",
      "sort_order": 1,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": null,
    "young_price": 99,
    "discount_percent": null,
    "discount_amount": null,
    "advantage_type": "special_rate",
    "age_min": 16,
    "age_max": 25,
    "student_required": false,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.sbb.ch/de/abos-billette/abos/ga/ga-night.html",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "UNTER_25",
      "SCHWEIZWEIT",
      "ONLINE"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": "https://www.sbb.ch",
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 142,
    "click_count": 58,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111102",
    "slug": "sbb-halbtax-jugend",
    "title_de": "SBB Halbtax Jugend: CHF 120.\u2013 statt CHF 190.\u2013 im 1. Jahr",
    "title_fr": "SBB Halbtax Jugend: CHF 120.\u2013 statt CHF 190.\u2013 im 1. Jahr",
    "title_it": "SBB Halbtax Jugend: CHF 120.\u2013 statt CHF 190.\u2013 im 1. Jahr",
    "description_de": "Das Halbtax Jugend der SBB f\u00fcr Jugendliche von 16 bis 25 Jahren zum reduzierten Erstjahr-Preis.",
    "description_fr": "Das Halbtax Jugend der SBB f\u00fcr Jugendliche von 16 bis 25 Jahren zum reduzierten Erstjahr-Preis.",
    "description_it": "Das Halbtax Jugend der SBB f\u00fcr Jugendliche von 16 bis 25 Jahren zum reduzierten Erstjahr-Preis.",
    "conditions_de": "50% Rabatt auf fast allen \u00d6V-Strecken der Schweiz. G\u00fcltig f\u00fcr Personen von 16 bis 25 Jahren.",
    "how_to_get_de": "1. Swisspass-Konto erstellen\n2. Ausweis hochladen\n3. Halbtax Jugend f\u00fcr CHF 120.\u2013 bestellen",
    "brand_id": "b-sbb",
    "brand": {
      "id": "b-sbb",
      "slug": "sbb",
      "name": "SBB CFF FFS",
      "logo_url": null,
      "description_de": "Der f\u00fchrende Schweizer \u00d6V-Anbieter mit speziellen Tarifen f\u00fcr Jugendliche und Studierende.",
      "website_url": "https://www.sbb.ch",
      "categories": [
        "reisen"
      ],
      "created_at": "2026-09-26T02:48:56.626Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-reisen",
    "category": {
      "id": "cat-reisen",
      "slug": "reisen",
      "name_de": "Reisen & \u00d6V",
      "name_fr": "Reisen & \u00d6V",
      "name_it": "Reisen & \u00d6V",
      "icon": "\ud83d\ude86",
      "description_de": "Angebote in Reisen & \u00d6V",
      "sort_order": 1,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 190,
    "young_price": 120,
    "discount_percent": 37,
    "discount_amount": 70,
    "advantage_type": "reduced_price",
    "age_min": 16,
    "age_max": 25,
    "student_required": false,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.sbb.ch/de/abos-billette/abos/halbtax.html",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "BELIEBT",
      "UNTER_25",
      "SCHWEIZWEIT"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": "https://www.sbb.ch",
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 210,
    "click_count": 89,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111103",
    "slug": "swisspass-partner-vorteile",
    "title_de": "Swisspass Partner-Vorteile: Verg\u00fcnstigte Nutzung",
    "title_fr": "Swisspass Partner-Vorteile: Verg\u00fcnstigte Nutzung",
    "title_it": "Swisspass Partner-Vorteile: Verg\u00fcnstigte Nutzung",
    "description_de": "Verg\u00fcnstigungen auf Partner-Dienste wie PubliBike und Carsharing mit dem Swisspass.",
    "description_fr": "Verg\u00fcnstigungen auf Partner-Dienste wie PubliBike und Carsharing mit dem Swisspass.",
    "description_it": "Verg\u00fcnstigungen auf Partner-Dienste wie PubliBike und Carsharing mit dem Swisspass.",
    "conditions_de": "Setzt eine aktive Swisspass-Karte voraus.",
    "how_to_get_de": "1. Swisspass Portal aufrufen\n2. Partner-Angebote verkn\u00fcpfen\n3. Erm\u00e4ssigungen nutzen",
    "brand_id": "b-swisspass",
    "brand": {
      "id": "b-swisspass",
      "slug": "swisspass",
      "name": "Alliance Swisspass",
      "logo_url": null,
      "description_de": "Partner Alliance Swisspass in der Schweiz",
      "website_url": "https://www.swisspass.ch",
      "categories": [
        "reisen"
      ],
      "created_at": "2026-09-26T02:48:56.626Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-reisen",
    "category": {
      "id": "cat-reisen",
      "slug": "reisen",
      "name_de": "Reisen & \u00d6V",
      "name_fr": "Reisen & \u00d6V",
      "name_it": "Reisen & \u00d6V",
      "icon": "\ud83d\ude86",
      "description_de": "Angebote in Reisen & \u00d6V",
      "sort_order": 1,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": null,
    "young_price": null,
    "discount_percent": null,
    "discount_amount": null,
    "advantage_type": "free",
    "age_min": 16,
    "age_max": 30,
    "student_required": false,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.swisspass.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "GRATIS",
      "SCHWEIZWEIT"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": "https://www.swisspass.ch",
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 88,
    "click_count": 24,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111104",
    "slug": "neon-free-banking",
    "title_de": "Neon Free Girokonto: Keine Kartengeb\u00fchren",
    "title_fr": "Neon Free Girokonto: Keine Kartengeb\u00fchren",
    "title_it": "Neon Free Girokonto: Keine Kartengeb\u00fchren",
    "description_de": "Geb\u00fchrenfreies Neobank-Konto mit Mastercard und ohne Aufschl\u00e4ge bei Auslandstransaktionen.",
    "description_fr": "Geb\u00fchrenfreies Neobank-Konto mit Mastercard und ohne Aufschl\u00e4ge bei Auslandstransaktionen.",
    "description_it": "Geb\u00fchrenfreies Neobank-Konto mit Mastercard und ohne Aufschl\u00e4ge bei Auslandstransaktionen.",
    "conditions_de": "Wohnsitz in der Schweiz und Alter ab 16 Jahren.",
    "how_to_get_de": "1. Neon App installieren\n2. Ausweis via Smartphone verifizieren\n3. Konto geb\u00fchrenfrei nutzen",
    "brand_id": "b-neon",
    "brand": {
      "id": "b-neon",
      "slug": "neon",
      "name": "Neon Bank",
      "logo_url": null,
      "description_de": "Schweizer Neobanking-L\u00f6sung mit geb\u00fchrenfreiem Girokonto und Mastercard.",
      "website_url": "https://www.neon-free.ch",
      "categories": [
        "finanzen"
      ],
      "created_at": "2026-09-26T02:48:56.626Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-finanzen",
    "category": {
      "id": "cat-finanzen",
      "slug": "finanzen",
      "name_de": "Finanzen & Banking",
      "name_fr": "Finanzen & Banking",
      "name_it": "Finanzen & Banking",
      "icon": "\ud83d\udcb3",
      "description_de": "Angebote in Finanzen & Banking",
      "sort_order": 2,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": null,
    "young_price": null,
    "discount_percent": null,
    "discount_amount": null,
    "advantage_type": "free",
    "age_min": 16,
    "age_max": 30,
    "student_required": false,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.neon-free.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "BELIEBT",
      "GRATIS",
      "ONLINE"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": "https://www.neon-free.ch",
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 195,
    "click_count": 82,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111105",
    "slug": "yuh-banking-app",
    "title_de": "Yuh Finanz-App: Kostenloses Konto ohne Grundgeb\u00fchr",
    "title_fr": "Yuh Finanz-App: Kostenloses Konto ohne Grundgeb\u00fchr",
    "title_it": "Yuh Finanz-App: Kostenloses Konto ohne Grundgeb\u00fchr",
    "description_de": "Schweizer Finanz-App von PostFinance und Swissquote mit Gratis-Konto und Zinsen.",
    "description_fr": "Schweizer Finanz-App von PostFinance und Swissquote mit Gratis-Konto und Zinsen.",
    "description_it": "Schweizer Finanz-App von PostFinance und Swissquote mit Gratis-Konto und Zinsen.",
    "conditions_de": "Wohnsitz in der Schweiz, Mindestalter 18 Jahre.",
    "how_to_get_de": "1. Yuh App herunterladen\n2. Registrieren & Ausweis hochladen\n3. Kostenloses Konto er\u00f6ffnen",
    "brand_id": "b-yuh",
    "brand": {
      "id": "b-yuh",
      "slug": "yuh",
      "name": "Yuh Schweiz",
      "logo_url": null,
      "description_de": "Schweizer Finanz-App von PostFinance und Swissquote f\u00fcr Sparen, Bezahlen und Investieren.",
      "website_url": "https://www.yuh.com",
      "categories": [
        "finanzen"
      ],
      "created_at": "2026-09-26T02:48:56.626Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-finanzen",
    "category": {
      "id": "cat-finanzen",
      "slug": "finanzen",
      "name_de": "Finanzen & Banking",
      "name_fr": "Finanzen & Banking",
      "name_it": "Finanzen & Banking",
      "icon": "\ud83d\udcb3",
      "description_de": "Angebote in Finanzen & Banking",
      "sort_order": 2,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": null,
    "young_price": null,
    "discount_percent": null,
    "discount_amount": null,
    "advantage_type": "free",
    "age_min": 18,
    "age_max": 30,
    "student_required": false,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.yuh.com",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "GRATIS",
      "ONLINE"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": "https://www.yuh.com",
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 160,
    "click_count": 64,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111106",
    "slug": "zkb-young-paket",
    "title_de": "ZKB young Konto: Konto ohne Grundgeb\u00fchr & ZVV-Nachtnetz",
    "title_fr": "ZKB young Konto: Konto ohne Grundgeb\u00fchr & ZVV-Nachtnetz",
    "title_it": "ZKB young Konto: Konto ohne Grundgeb\u00fchr & ZVV-Nachtnetz",
    "description_de": "Jugendkonto der Z\u00fcrcher Kantonalbank mit kostenlosem ZVV-Nachtschw\u00e4rmer f\u00fcr Jugendliche bis 30 Jahre.",
    "description_fr": "Jugendkonto der Z\u00fcrcher Kantonalbank mit kostenlosem ZVV-Nachtschw\u00e4rmer f\u00fcr Jugendliche bis 30 Jahre.",
    "description_it": "Jugendkonto der Z\u00fcrcher Kantonalbank mit kostenlosem ZVV-Nachtschw\u00e4rmer f\u00fcr Jugendliche bis 30 Jahre.",
    "conditions_de": "Bis 30 Jahre im Kanton Z\u00fcrich.",
    "how_to_get_de": "1. ZKB young App herunterladen\n2. Identifikation abschliessen\n3. ZVV Nacht-Vorteil aktivieren",
    "brand_id": "b-zkb",
    "brand": {
      "id": "b-zkb",
      "slug": "zkb",
      "name": "Z\u00fcrcher Kantonalbank",
      "logo_url": null,
      "description_de": "Kantonalbank-Angebote mit ZVV-Verg\u00fcnstigungen und Gratiskonten f\u00fcr Jugendliche.",
      "website_url": "https://www.zkb.ch",
      "categories": [
        "finanzen"
      ],
      "created_at": "2026-09-26T02:48:56.626Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-finanzen",
    "category": {
      "id": "cat-finanzen",
      "slug": "finanzen",
      "name_de": "Finanzen & Banking",
      "name_fr": "Finanzen & Banking",
      "name_it": "Finanzen & Banking",
      "icon": "\ud83d\udcb3",
      "description_de": "Angebote in Finanzen & Banking",
      "sort_order": 2,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": null,
    "young_price": null,
    "discount_percent": null,
    "discount_amount": null,
    "advantage_type": "free",
    "age_min": 16,
    "age_max": 30,
    "student_required": false,
    "city_id": "c-zurich",
    "canton": "ZH",
    "is_nationwide": false,
    "is_online": true,
    "external_url": "https://www.zkb.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "ZUERICH",
      "UNTER_30",
      "GRATIS"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": "https://www.zkb.ch",
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 130,
    "click_count": 41,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111107",
    "slug": "ipv-praemienverbilligung-schweiz",
    "title_de": "Krankenkassen-Pr\u00e4mienverbilligung (IPV)",
    "title_fr": "Krankenkassen-Pr\u00e4mienverbilligung (IPV)",
    "title_it": "Krankenkassen-Pr\u00e4mienverbilligung (IPV)",
    "description_de": "M\u00f6gliche finanzielle Unterst\u00fctzung zur Senkung der Krankenkassenpr\u00e4mien je nach Kanton und Einkommen.",
    "description_fr": "M\u00f6gliche finanzielle Unterst\u00fctzung zur Senkung der Krankenkassenpr\u00e4mien je nach Kanton und Einkommen.",
    "description_it": "M\u00f6gliche finanzielle Unterst\u00fctzung zur Senkung der Krankenkassenpr\u00e4mien je nach Kanton und Einkommen.",
    "conditions_de": "Abh\u00e4ngig von steuerbarem Einkommen, Wohnsitzkanton und Ausbildungsstatus.",
    "how_to_get_de": "1. Kantonsportal SVA/ASV aufrufen\n2. Steuerdaten & Ausbildungsnachweis bereithalten\n3. Antrag fristgerecht online einreichen",
    "brand_id": "b-sva",
    "brand": {
      "id": "b-sva",
      "slug": "sva",
      "name": "SVA / Kantonale Sozialversicherung",
      "logo_url": null,
      "description_de": "Kantonale Ausgleichskassen und Sozialversicherungen der Schweiz.",
      "website_url": "https://www.sva.ch",
      "categories": [
        "krankenkasse"
      ],
      "created_at": "2026-09-26T02:48:56.626Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-krankenkasse",
    "category": {
      "id": "cat-krankenkasse",
      "slug": "krankenkasse",
      "name_de": "Krankenkasse & IPV",
      "name_fr": "Krankenkasse & IPV",
      "name_it": "Krankenkasse & IPV",
      "icon": "\ud83e\ude7a",
      "description_de": "Angebote in Krankenkasse & IPV",
      "sort_order": 1,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": null,
    "young_price": null,
    "discount_percent": null,
    "discount_amount": null,
    "advantage_type": "special_rate",
    "age_min": 16,
    "age_max": 30,
    "student_required": true,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.sva.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "STUDENTEN",
      "SCHWEIZWEIT",
      "ONLINE"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": "https://www.sva.ch",
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 120,
    "click_count": 45,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111108",
    "slug": "sanitas-fitness-cashback",
    "title_de": "Sanitas Sport-Cashback: Bis zu CHF 500.\u2013 Cashback f\u00fcr Gym & Sport",
    "title_fr": "Sanitas Sport-Cashback: Bis zu CHF 500.\u2013 Cashback f\u00fcr Gym & Sport",
    "title_it": "Sanitas Sport-Cashback: Bis zu CHF 500.\u2013 Cashback f\u00fcr Gym & Sport",
    "description_de": "Cashback-Beitr\u00e4ge von Sanitas an Fitnessabos und Sportmitgliedschaften f\u00fcr Zusatzversicherte.",
    "description_fr": "Cashback-Beitr\u00e4ge von Sanitas an Fitnessabos und Sportmitgliedschaften f\u00fcr Zusatzversicherte.",
    "description_it": "Cashback-Beitr\u00e4ge von Sanitas an Fitnessabos und Sportmitgliedschaften f\u00fcr Zusatzversicherte.",
    "conditions_de": "Erfordert QualiCert-zertifiziertes Gym oder Zusatzversicherung.",
    "how_to_get_de": "1. Sportabo oder ASVZ-Quittung einreichen\n2. \u00dcber Sanitas Portal hochladen\n3. Bis zu CHF 500.\u2013 R\u00fcckerstattung erhalten",
    "brand_id": "b-sanitas",
    "brand": {
      "id": "b-sanitas",
      "slug": "sanitas",
      "name": "Sanitas Krankenversicherung",
      "logo_url": null,
      "description_de": "Schweizer Krankenversicherung mit Sport-Cashback und Pr\u00e4mienrabatten.",
      "website_url": "https://www.sanitas.com",
      "categories": [
        "krankenkasse"
      ],
      "created_at": "2026-09-26T02:48:56.626Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-krankenkasse",
    "category": {
      "id": "cat-krankenkasse",
      "slug": "krankenkasse",
      "name_de": "Krankenkasse & IPV",
      "name_fr": "Krankenkasse & IPV",
      "name_it": "Krankenkasse & IPV",
      "icon": "\ud83e\ude7a",
      "description_de": "Angebote in Krankenkasse & IPV",
      "sort_order": 1,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": null,
    "young_price": null,
    "discount_percent": null,
    "discount_amount": 500,
    "advantage_type": "cashback",
    "age_min": 16,
    "age_max": 30,
    "student_required": false,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.sanitas.com",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "SCHWEIZWEIT",
      "ONLINE"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": "https://www.sanitas.com",
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 94,
    "click_count": 31,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111109",
    "slug": "woko-studenten-wgs",
    "title_de": "WOKO Z\u00fcrcher Studentenzimmer ab CHF 500.\u2013 / Monat",
    "title_fr": "WOKO Z\u00fcrcher Studentenzimmer ab CHF 500.\u2013 / Monat",
    "title_it": "WOKO Z\u00fcrcher Studentenzimmer ab CHF 500.\u2013 / Monat",
    "description_de": "G\u00fcnstige Studentenzimmer der Wohngenossenschaft WOKO im Raum Z\u00fcrich.",
    "description_fr": "G\u00fcnstige Studentenzimmer der Wohngenossenschaft WOKO im Raum Z\u00fcrich.",
    "description_it": "G\u00fcnstige Studentenzimmer der Wohngenossenschaft WOKO im Raum Z\u00fcrich.",
    "conditions_de": "F\u00fcr immatrikulierte Studierende der UZH, ETH und ZHAW.",
    "how_to_get_de": "1. Inserate auf woko.ch pr\u00fcfen\n2. Bei Zimmer-WG bewerben\n3. Mietvertrag abschliessen",
    "brand_id": "b-woko",
    "brand": {
      "id": "b-woko",
      "slug": "woko",
      "name": "WOKO Wohngenossenschaft",
      "logo_url": null,
      "description_de": "Wohngenossenschaft f\u00fcr Studierende im Kanton Z\u00fcrich.",
      "website_url": "https://www.woko.ch",
      "categories": [
        "wohnen"
      ],
      "created_at": "2026-09-26T02:48:56.626Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-wohnen",
    "category": {
      "id": "cat-wohnen",
      "slug": "wohnen",
      "name_de": "Wohnen & WG",
      "name_fr": "Wohnen & WG",
      "name_it": "Wohnen & WG",
      "icon": "\ud83c\udfe0",
      "description_de": "Angebote in Wohnen & WG",
      "sort_order": 3,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": null,
    "young_price": 500,
    "discount_percent": null,
    "discount_amount": null,
    "advantage_type": "special_rate",
    "age_min": 18,
    "age_max": 28,
    "student_required": true,
    "city_id": "c-zurich",
    "canton": "ZH",
    "is_nationwide": false,
    "is_online": true,
    "external_url": "https://www.woko.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "ZUERICH",
      "STUDENTEN"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": "https://www.woko.ch",
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 180,
    "click_count": 72,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111110",
    "slug": "fmel-lausanne-housing",
    "title_de": "FMEL Studentengeb\u00e4ude Lausanne ab CHF 550.\u2013 / Monat",
    "title_fr": "FMEL Studentengeb\u00e4ude Lausanne ab CHF 550.\u2013 / Monat",
    "title_it": "FMEL Studentengeb\u00e4ude Lausanne ab CHF 550.\u2013 / Monat",
    "description_de": "Studentenwohnheime der FMEL f\u00fcr Studierende an der UNIL und EPFL in Lausanne.",
    "description_fr": "Studentenwohnheime der FMEL f\u00fcr Studierende an der UNIL und EPFL in Lausanne.",
    "description_it": "Studentenwohnheime der FMEL f\u00fcr Studierende an der UNIL und EPFL in Lausanne.",
    "conditions_de": "F\u00fcr immatrikulierte UNIL / EPFL Studierende.",
    "how_to_get_de": "1. FMEL Online-Portal aufrufen\n2. Bewerbung einreichen\n3. Immatrikulation hochladen",
    "brand_id": "b-fmel",
    "brand": {
      "id": "b-fmel",
      "slug": "fmel",
      "name": "FMEL Lausanne",
      "logo_url": null,
      "description_de": "Stiftung f\u00fcr Studentisches Wohnen im Kanton Waadt.",
      "website_url": "https://www.fmel.ch",
      "categories": [
        "wohnen"
      ],
      "created_at": "2026-09-26T02:48:56.626Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-wohnen",
    "category": {
      "id": "cat-wohnen",
      "slug": "wohnen",
      "name_de": "Wohnen & WG",
      "name_fr": "Wohnen & WG",
      "name_it": "Wohnen & WG",
      "icon": "\ud83c\udfe0",
      "description_de": "Angebote in Wohnen & WG",
      "sort_order": 3,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": null,
    "young_price": 550,
    "discount_percent": null,
    "discount_amount": null,
    "advantage_type": "special_rate",
    "age_min": 18,
    "age_max": 30,
    "student_required": true,
    "city_id": "c-lausanne",
    "canton": "VD",
    "is_nationwide": false,
    "is_online": true,
    "external_url": "https://www.fmel.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "STUDENTEN"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": "https://www.fmel.ch",
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 76,
    "click_count": 29,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111111",
    "slug": "salt-youth-mobile",
    "title_de": "Salt Youth Abo: 5G Flatrate f\u00fcr CHF 24.95 / Monat",
    "title_fr": "Salt Youth Abo: 5G Flatrate f\u00fcr CHF 24.95 / Monat",
    "title_it": "Salt Youth Abo: 5G Flatrate f\u00fcr CHF 24.95 / Monat",
    "description_de": "Schweizer Handy-Jugendabo von Salt mit Datenvolumen und 5G-Netzwerk.",
    "description_fr": "Schweizer Handy-Jugendabo von Salt mit Datenvolumen und 5G-Netzwerk.",
    "description_it": "Schweizer Handy-Jugendabo von Salt mit Datenvolumen und 5G-Netzwerk.",
    "conditions_de": "G\u00fcltig f\u00fcr Jugendliche unter 30 Jahren.",
    "how_to_get_de": "1. Salt Store oder Online-Shop besuchen\n2. Ausweis vorlegen\n3. Jugend-Tarif w\u00e4hlen",
    "brand_id": "b-salt",
    "brand": {
      "id": "b-salt",
      "slug": "salt",
      "name": "Salt Mobile",
      "logo_url": null,
      "description_de": "Mobilfunkanbieter mit Jugend- und Studententarifen in der Schweiz.",
      "website_url": "https://www.salt.ch",
      "categories": [
        "technik"
      ],
      "created_at": "2026-09-26T02:48:56.626Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-technik",
    "category": {
      "id": "cat-technik",
      "slug": "technik",
      "name_de": "Technik & Handy",
      "name_fr": "Technik & Handy",
      "name_it": "Technik & Handy",
      "icon": "\ud83d\udcf1",
      "description_de": "Angebote in Technik & Handy",
      "sort_order": 4,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 59.95,
    "young_price": 24.95,
    "discount_percent": 58,
    "discount_amount": 35,
    "advantage_type": "reduced_price",
    "age_min": 16,
    "age_max": 30,
    "student_required": false,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.salt.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "UNTER_30",
      "SCHWEIZWEIT",
      "ONLINE"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": "https://www.salt.ch",
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 145,
    "click_count": 52,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111112",
    "slug": "swisscom-blue-youth",
    "title_de": "Swisscom blue Mobile Youth: 5G-Jugendtarif ab CHF 24.90 / Monat",
    "title_fr": "Swisscom blue Mobile Youth: 5G-Jugendtarif ab CHF 24.90 / Monat",
    "title_it": "Swisscom blue Mobile Youth: 5G-Jugendtarif ab CHF 24.90 / Monat",
    "description_de": "Swisscom Jugendtarife mit 5G-Abdeckung und Auslandsoptionen.",
    "description_fr": "Swisscom Jugendtarife mit 5G-Abdeckung und Auslandsoptionen.",
    "description_it": "Swisscom Jugendtarife mit 5G-Abdeckung und Auslandsoptionen.",
    "conditions_de": "Unter 30 Jahre in der Schweiz.",
    "how_to_get_de": "1. Swisscom Youth Shop besuchen\n2. Angebot w\u00e4hlen\n3. Vertrag abschliessen",
    "brand_id": "b-swisscom",
    "brand": {
      "id": "b-swisscom",
      "slug": "swisscom",
      "name": "Swisscom",
      "logo_url": null,
      "description_de": "Schweizer Telefondienstleister mit 5G-Jugendtarifen.",
      "website_url": "https://www.swisscom.ch",
      "categories": [
        "technik"
      ],
      "created_at": "2026-09-26T02:48:56.626Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-technik",
    "category": {
      "id": "cat-technik",
      "slug": "technik",
      "name_de": "Technik & Handy",
      "name_fr": "Technik & Handy",
      "name_it": "Technik & Handy",
      "icon": "\ud83d\udcf1",
      "description_de": "Angebote in Technik & Handy",
      "sort_order": 4,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 69.9,
    "young_price": 24.9,
    "discount_percent": 64,
    "discount_amount": 45,
    "advantage_type": "reduced_price",
    "age_min": 16,
    "age_max": 30,
    "student_required": false,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.swisscom.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "BELIEBT",
      "UNTER_30",
      "SCHWEIZWEIT"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": "https://www.swisscom.ch",
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 168,
    "click_count": 61,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111113",
    "slug": "projekt-neptun-laptops",
    "title_de": "Projekt Neptun: Bis zu 40% Rabatt auf Laptops & MacBooks",
    "title_fr": "Projekt Neptun: Bis zu 40% Rabatt auf Laptops & MacBooks",
    "title_it": "Projekt Neptun: Bis zu 40% Rabatt auf Laptops & MacBooks",
    "description_de": "Semestrale Verkaufsfenster f\u00fcr Laptops, MacBooks und Tablets mit Hochschulrabatt.",
    "description_fr": "Semestrale Verkaufsfenster f\u00fcr Laptops, MacBooks und Tablets mit Hochschulrabatt.",
    "description_it": "Semestrale Verkaufsfenster f\u00fcr Laptops, MacBooks und Tablets mit Hochschulrabatt.",
    "conditions_de": "G\u00fcltig f\u00fcr Studierende, Auszubildende und Lehrpersonen an Schweizer Hochschulen.",
    "how_to_get_de": "1. Verkaufsfenster abwarten (Fr\u00fchling/Herbst)\n2. Mit Switch edu-ID einloggen\n3. Rabattierten Laptop bestellen",
    "brand_id": "b-neptun",
    "brand": {
      "id": "b-neptun",
      "slug": "neptun",
      "name": "Projekt Neptun",
      "logo_url": null,
      "description_de": "Schweizer Plattform f\u00fcr Laptops und Tablets an Hochschulen.",
      "website_url": "https://projektneptun.ch",
      "categories": [
        "technik"
      ],
      "created_at": "2026-09-26T02:48:56.626Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-technik",
    "category": {
      "id": "cat-technik",
      "slug": "technik",
      "name_de": "Technik & Handy",
      "name_fr": "Technik & Handy",
      "name_it": "Technik & Handy",
      "icon": "\ud83d\udcf1",
      "description_de": "Angebote in Technik & Handy",
      "sort_order": 4,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": null,
    "young_price": null,
    "discount_percent": 40,
    "discount_amount": null,
    "advantage_type": "discount_percent",
    "age_min": 16,
    "age_max": 30,
    "student_required": true,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://projektneptun.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "STUDENTEN",
      "ONLINE"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": "https://projektneptun.ch",
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 230,
    "click_count": 94,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111114",
    "slug": "apple-education-store",
    "title_de": "Apple Education Store: 10% Bildungsrabatt auf Macs & iPads",
    "title_fr": "Apple Education Store: 10% Bildungsrabatt auf Macs & iPads",
    "title_it": "Apple Education Store: 10% Bildungsrabatt auf Macs & iPads",
    "description_de": "Bildungspreise im offiziellen Schweizer Apple Store f\u00fcr Studierende und Lehrpersonen.",
    "description_fr": "Bildungspreise im offiziellen Schweizer Apple Store f\u00fcr Studierende und Lehrpersonen.",
    "description_it": "Bildungspreise im offiziellen Schweizer Apple Store f\u00fcr Studierende und Lehrpersonen.",
    "conditions_de": "Nachweis des Studentenstatus via UNiDAYS oder Ausweis.",
    "how_to_get_de": "1. Apple Education Store Schweiz aufrufen\n2. Studentenstatus verifizieren\n3. Bildungsrabatt nutzen",
    "brand_id": "b-apple",
    "brand": {
      "id": "b-apple",
      "slug": "apple",
      "name": "Apple Store Switzerland",
      "logo_url": null,
      "description_de": "Offizielle Bildungsrabatte f\u00fcr Mac und iPad an Schweizer Universit\u00e4ten.",
      "website_url": "https://www.apple.com/ch-edu/shop",
      "categories": [
        "technik"
      ],
      "created_at": "2026-09-26T02:48:56.626Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-technik",
    "category": {
      "id": "cat-technik",
      "slug": "technik",
      "name_de": "Technik & Handy",
      "name_fr": "Technik & Handy",
      "name_it": "Technik & Handy",
      "icon": "\ud83d\udcf1",
      "description_de": "Angebote in Technik & Handy",
      "sort_order": 4,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": null,
    "young_price": null,
    "discount_percent": 10,
    "discount_amount": null,
    "advantage_type": "discount_percent",
    "age_min": 18,
    "age_max": 30,
    "student_required": true,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.apple.com/ch-edu/shop",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "BELIEBT",
      "STUDENTEN",
      "ONLINE"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": "https://www.apple.com/ch-edu/shop",
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 290,
    "click_count": 115,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111115",
    "slug": "spotify-student-discount",
    "title_de": "Spotify Premium Student: CHF 6.95 / Monat statt CHF 13.90",
    "title_fr": "Spotify Premium Student: CHF 6.95 / Monat statt CHF 13.90",
    "title_it": "Spotify Premium Student: CHF 6.95 / Monat statt CHF 13.90",
    "description_de": "Spotify Premium Student zum reduzierten Monatspreis f\u00fcr immatrikulierte Studierende.",
    "description_fr": "Spotify Premium Student zum reduzierten Monatspreis f\u00fcr immatrikulierte Studierende.",
    "description_it": "Spotify Premium Student zum reduzierten Monatspreis f\u00fcr immatrikulierte Studierende.",
    "conditions_de": "Verifizierung \u00fcber SheerID f\u00fcr immatrikulierte Studierende.",
    "how_to_get_de": "1. Spotify Student Landingpage aufrufen\n2. Hochschule ausw\u00e4hlen & SheerID verifizieren\n3. CHF 6.95/Monat zahlen",
    "brand_id": "b-spotify",
    "brand": {
      "id": "b-spotify",
      "slug": "spotify",
      "name": "Spotify",
      "logo_url": null,
      "description_de": "Musik-Streaming-Anbieter mit verifizierten Studierendenrabatten.",
      "website_url": "https://www.spotify.com/ch-de/student/",
      "categories": [
        "lifestyle"
      ],
      "created_at": "2026-09-26T02:48:56.626Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-lifestyle",
    "category": {
      "id": "cat-lifestyle",
      "slug": "lifestyle",
      "name_de": "Entertainment & Gaming",
      "name_fr": "Entertainment & Gaming",
      "name_it": "Entertainment & Gaming",
      "icon": "\ud83c\udfae",
      "description_de": "Angebote in Entertainment & Gaming",
      "sort_order": 5,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 13.9,
    "young_price": 6.95,
    "discount_percent": 50,
    "discount_amount": 6.95,
    "advantage_type": "reduced_price",
    "age_min": 18,
    "age_max": 30,
    "student_required": true,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.spotify.com/ch-de/student/",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "BELIEBT",
      "STUDENTEN",
      "ONLINE"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": "https://www.spotify.com",
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 310,
    "click_count": 140,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111116",
    "slug": "youtube-premium-student",
    "title_de": "YouTube Premium Student: CHF 9.90 / Monat statt CHF 15.90",
    "title_fr": "YouTube Premium Student: CHF 9.90 / Monat statt CHF 15.90",
    "title_it": "YouTube Premium Student: CHF 9.90 / Monat statt CHF 15.90",
    "description_de": "YouTube Premium Studententarif f\u00fcr werbefreie Videos und Musik-Streaming.",
    "description_fr": "YouTube Premium Studententarif f\u00fcr werbefreie Videos und Musik-Streaming.",
    "description_it": "YouTube Premium Studententarif f\u00fcr werbefreie Videos und Musik-Streaming.",
    "conditions_de": "SheerID Best\u00e4tigung des Studentenstatus.",
    "how_to_get_de": "1. YouTube Premium Student Tarif w\u00e4hlen\n2. Universit\u00e4t ausw\u00e4hlen\n3. Rabattierten Preis aktivieren",
    "brand_id": "b-youtube",
    "brand": {
      "id": "b-youtube",
      "slug": "youtube",
      "name": "YouTube CH",
      "logo_url": null,
      "description_de": "Video- und Musik-Streaming-Plattform mit Studentstarifen.",
      "website_url": "https://www.youtube.com/premium/student",
      "categories": [
        "lifestyle"
      ],
      "created_at": "2026-09-26T02:48:56.626Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-lifestyle",
    "category": {
      "id": "cat-lifestyle",
      "slug": "lifestyle",
      "name_de": "Entertainment & Gaming",
      "name_fr": "Entertainment & Gaming",
      "name_it": "Entertainment & Gaming",
      "icon": "\ud83c\udfae",
      "description_de": "Angebote in Entertainment & Gaming",
      "sort_order": 5,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 15.9,
    "young_price": 9.9,
    "discount_percent": 38,
    "discount_amount": 6.0,
    "advantage_type": "reduced_price",
    "age_min": 18,
    "age_max": 30,
    "student_required": true,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.youtube.com/premium/student",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "STUDENTEN",
      "ONLINE"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": "https://www.youtube.com",
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 185,
    "click_count": 67,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111117",
    "slug": "zalando-studentenrabatt",
    "title_de": "Zalando Studententarif: 10% Rabatt auf Mode & Schuhe",
    "title_fr": "Zalando Studententarif: 10% Rabatt auf Mode & Schuhe",
    "title_it": "Zalando Studententarif: 10% Rabatt auf Mode & Schuhe",
    "description_de": "Rabattcodes und Sonderaktionen f\u00fcr Mode und Schuhe im Schweizer Zalando Store.",
    "description_fr": "Rabattcodes und Sonderaktionen f\u00fcr Mode und Schuhe im Schweizer Zalando Store.",
    "description_it": "Rabattcodes und Sonderaktionen f\u00fcr Mode und Schuhe im Schweizer Zalando Store.",
    "conditions_de": "Mindestbestellwert CHF 50.\u2013.",
    "how_to_get_de": "1. Zalando Student Partner-Code abrufen\n2. Im Warenkorb eingeben\n3. 10% sparen",
    "brand_id": "b-zalando",
    "brand": {
      "id": "b-zalando",
      "slug": "zalando",
      "name": "Zalando Schweiz",
      "logo_url": null,
      "description_de": "Online-Mode-H\u00e4ndler mit regelm\u00e4ssigen Aktionen und Gutscheinen.",
      "website_url": "https://www.zalando.ch",
      "categories": [
        "lifestyle"
      ],
      "created_at": "2026-09-26T02:48:56.626Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-lifestyle",
    "category": {
      "id": "cat-lifestyle",
      "slug": "lifestyle",
      "name_de": "Entertainment & Gaming",
      "name_fr": "Entertainment & Gaming",
      "name_it": "Entertainment & Gaming",
      "icon": "\ud83c\udfae",
      "description_de": "Angebote in Entertainment & Gaming",
      "sort_order": 5,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": null,
    "young_price": null,
    "discount_percent": 10,
    "discount_amount": null,
    "advantage_type": "discount_percent",
    "age_min": 16,
    "age_max": 30,
    "student_required": true,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.zalando.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "STUDENTEN",
      "ONLINE"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": "https://www.zalando.ch",
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 150,
    "click_count": 48,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111118",
    "slug": "nike-student-discount",
    "title_de": "Nike Store: 10% Studentenrabatt auf Sportkleidung",
    "title_fr": "Nike Store: 10% Studentenrabatt auf Sportkleidung",
    "title_it": "Nike Store: 10% Studentenrabatt auf Sportkleidung",
    "description_de": "Preisnachl\u00e4sse im Nike Online Store f\u00fcr verifizierte Studierende.",
    "description_fr": "Preisnachl\u00e4sse im Nike Online Store f\u00fcr verifizierte Studierende.",
    "description_it": "Preisnachl\u00e4sse im Nike Online Store f\u00fcr verifizierte Studierende.",
    "conditions_de": "G\u00fcltig im Nike Online Store Schweiz.",
    "how_to_get_de": "1. UNiDAYS Status verifizieren\n2. Nike Gutscheincode generieren\n3. Beim Checkout einl\u00f6sen",
    "brand_id": "b-nike",
    "brand": {
      "id": "b-nike",
      "slug": "nike",
      "name": "Nike CH",
      "logo_url": null,
      "description_de": "Sport- und Lifestyle-Marke mit Rabatten f\u00fcr Lernende und Studierende.",
      "website_url": "https://www.nike.com/ch/",
      "categories": [
        "lifestyle"
      ],
      "created_at": "2026-09-26T02:48:56.626Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-lifestyle",
    "category": {
      "id": "cat-lifestyle",
      "slug": "lifestyle",
      "name_de": "Entertainment & Gaming",
      "name_fr": "Entertainment & Gaming",
      "name_it": "Entertainment & Gaming",
      "icon": "\ud83c\udfae",
      "description_de": "Angebote in Entertainment & Gaming",
      "sort_order": 5,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": null,
    "young_price": null,
    "discount_percent": 10,
    "discount_amount": null,
    "advantage_type": "discount_percent",
    "age_min": 16,
    "age_max": 30,
    "student_required": true,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.nike.com/ch/",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "STUDENTEN",
      "ONLINE"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": "https://www.nike.com/ch/",
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 140,
    "click_count": 42,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111119",
    "slug": "asvz-sport-mitgliedschaft",
    "title_de": "ASVZ Hochschulsport Z\u00fcrich: Gratis im Semesterbeitrag enthalten",
    "title_fr": "ASVZ Hochschulsport Z\u00fcrich: Gratis im Semesterbeitrag enthalten",
    "title_it": "ASVZ Hochschulsport Z\u00fcrich: Gratis im Semesterbeitrag enthalten",
    "description_de": "Sportangebot des ASVZ f\u00fcr UZH, ETH und ZHAW im Semesterbeitrag enthalten.",
    "description_fr": "Sportangebot des ASVZ f\u00fcr UZH, ETH und ZHAW im Semesterbeitrag enthalten.",
    "description_it": "Sportangebot des ASVZ f\u00fcr UZH, ETH und ZHAW im Semesterbeitrag enthalten.",
    "conditions_de": "F\u00fcr immatrikulierte Studierende der UZH, ETH und ZHAW.",
    "how_to_get_de": "1. Legi / Switch edu-ID bereithalten\n2. ASVZ App herunterladen\n3. Alle Sportzentren kostenlos nutzen",
    "brand_id": "b-asvz",
    "brand": {
      "id": "b-asvz",
      "slug": "asvz",
      "name": "ASVZ Akademischer Sportverband Z\u00fcrich",
      "logo_url": null,
      "description_de": "Akademischer Sportverband Z\u00fcrich f\u00fcr Studierende der UZH, ETH und ZHAW.",
      "website_url": "https://asvz.ch",
      "categories": [
        "sport"
      ],
      "created_at": "2026-09-26T02:48:56.626Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-sport",
    "category": {
      "id": "cat-sport",
      "slug": "sport",
      "name_de": "Sport & Fitness",
      "name_fr": "Sport & Fitness",
      "name_it": "Sport & Fitness",
      "icon": "\ud83c\udfcb\ufe0f",
      "description_de": "Angebote in Sport & Fitness",
      "sort_order": 6,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": null,
    "young_price": null,
    "discount_percent": null,
    "discount_amount": null,
    "advantage_type": "free",
    "age_min": 18,
    "age_max": 30,
    "student_required": true,
    "city_id": "c-zurich",
    "canton": "ZH",
    "is_nationwide": false,
    "is_online": true,
    "external_url": "https://asvz.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "ZUERICH",
      "STUDENTEN",
      "GRATIS"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": "https://asvz.ch",
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 250,
    "click_count": 105,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111120",
    "slug": "unisport-bern-access",
    "title_de": "UNISPORT Bern: Gratis im Semesterbeitrag enthalten",
    "title_fr": "UNISPORT Bern: Gratis im Semesterbeitrag enthalten",
    "title_it": "UNISPORT Bern: Gratis im Semesterbeitrag enthalten",
    "description_de": "Kostenloses und verg\u00fcnstigtes Sportangebot des Uni-Sports Bern.",
    "description_fr": "Kostenloses und verg\u00fcnstigtes Sportangebot des Uni-Sports Bern.",
    "description_it": "Kostenloses und verg\u00fcnstigtes Sportangebot des Uni-Sports Bern.",
    "conditions_de": "G\u00fcltig f\u00fcr Studierende der Uni Bern und BFH.",
    "how_to_get_de": "1. UniBE Legi vorweisen\n2. Kurse online buchen\n3. Gratis teilnehmen",
    "brand_id": "b-unisport-bern",
    "brand": {
      "id": "b-unisport-bern",
      "slug": "unisport-bern",
      "name": "UNISPORT Bern",
      "logo_url": null,
      "description_de": "Sportverband der Universit\u00e4t Bern und BFH.",
      "website_url": "https://www.unibe.ch/unisport",
      "categories": [
        "sport"
      ],
      "created_at": "2026-09-26T02:48:56.626Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-sport",
    "category": {
      "id": "cat-sport",
      "slug": "sport",
      "name_de": "Sport & Fitness",
      "name_fr": "Sport & Fitness",
      "name_it": "Sport & Fitness",
      "icon": "\ud83c\udfcb\ufe0f",
      "description_de": "Angebote in Sport & Fitness",
      "sort_order": 6,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": null,
    "young_price": null,
    "discount_percent": null,
    "discount_amount": null,
    "advantage_type": "free",
    "age_min": 18,
    "age_max": 30,
    "student_required": true,
    "city_id": "c-bern",
    "canton": "BE",
    "is_nationwide": false,
    "is_online": true,
    "external_url": "https://www.unibe.ch/unisport",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "STUDENTEN",
      "GRATIS"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": "https://www.unibe.ch",
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 92,
    "click_count": 34,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111121",
    "slug": "pathe-kino-student",
    "title_de": "Path\u00e9 Kino Kinomontag: Tickets f\u00fcr CHF 14.\u2013 statt CHF 22.\u2013",
    "title_fr": "Path\u00e9 Kino Kinomontag: Tickets f\u00fcr CHF 14.\u2013 statt CHF 22.\u2013",
    "title_it": "Path\u00e9 Kino Kinomontag: Tickets f\u00fcr CHF 14.\u2013 statt CHF 22.\u2013",
    "description_de": "Kino-Konditionen f\u00fcr Jugendliche und Studierende in den Schweizer Path\u00e9 Kinos.",
    "description_fr": "Kino-Konditionen f\u00fcr Jugendliche und Studierende in den Schweizer Path\u00e9 Kinos.",
    "description_it": "Kino-Konditionen f\u00fcr Jugendliche und Studierende in den Schweizer Path\u00e9 Kinos.",
    "conditions_de": "G\u00fcltig f\u00fcr Vorstellungen an Kinomontagen mit Legi.",
    "how_to_get_de": "1. Path\u00e9 App oder Kasse w\u00e4hlen\n2. Studententarif w\u00e4hlen\n3. CHF 14.\u2013 Ticket buchen",
    "brand_id": "b-pathe",
    "brand": {
      "id": "b-pathe",
      "slug": "pathe",
      "name": "Path\u00e9 Kinos Schweiz",
      "logo_url": null,
      "description_de": "Schweizer Kinokette mit Verg\u00fcnstigungen f\u00fcr Jugendliche.",
      "website_url": "https://www.pathe.ch",
      "categories": [
        "lifestyle"
      ],
      "created_at": "2026-09-26T02:48:56.626Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-lifestyle",
    "category": {
      "id": "cat-lifestyle",
      "slug": "lifestyle",
      "name_de": "Entertainment & Gaming",
      "name_fr": "Entertainment & Gaming",
      "name_it": "Entertainment & Gaming",
      "icon": "\ud83c\udfae",
      "description_de": "Angebote in Entertainment & Gaming",
      "sort_order": 5,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 22,
    "young_price": 14,
    "discount_percent": 36,
    "discount_amount": 8,
    "advantage_type": "reduced_price",
    "age_min": 16,
    "age_max": 30,
    "student_required": false,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.pathe.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "SCHWEIZWEIT"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": "https://www.pathe.ch",
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 110,
    "click_count": 39,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111122",
    "slug": "too-good-to-go-food",
    "title_de": "Too Good To Go: Essen retten ab CHF 4.90",
    "title_fr": "Too Good To Go: Essen retten ab CHF 4.90",
    "title_it": "Too Good To Go: Essen retten ab CHF 4.90",
    "description_de": "App zur Rettung \u00fcbersch\u00fcssiger Lebensmittel bei B\u00e4ckereien und Restaurants zu reduzierten Preisen.",
    "description_fr": "App zur Rettung \u00fcbersch\u00fcssiger Lebensmittel bei B\u00e4ckereien und Restaurants zu reduzierten Preisen.",
    "description_it": "App zur Rettung \u00fcbersch\u00fcssiger Lebensmittel bei B\u00e4ckereien und Restaurants zu reduzierten Preisen.",
    "conditions_de": "Abholung im angegebenen Zeitfenster beim Betrieb.",
    "how_to_get_de": "1. Too Good To Go App herunterladen\n2. \u00dcberraschungst\u00fcte reservieren\n3. Vor Ort abholen",
    "brand_id": "b-tgtg",
    "brand": {
      "id": "b-tgtg",
      "slug": "too-good-to-go",
      "name": "Too Good To Go CH",
      "logo_url": null,
      "description_de": "App zur Rettung \u00fcbersch\u00fcssiger Lebensmittel zu reduzierten Preisen in der Schweiz.",
      "website_url": "https://toogoodtogo.ch",
      "categories": [
        "lifestyle"
      ],
      "created_at": "2026-09-26T02:48:56.626Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-lifestyle",
    "category": {
      "id": "cat-lifestyle",
      "slug": "lifestyle",
      "name_de": "Entertainment & Gaming",
      "name_fr": "Entertainment & Gaming",
      "name_it": "Entertainment & Gaming",
      "icon": "\ud83c\udfae",
      "description_de": "Angebote in Entertainment & Gaming",
      "sort_order": 5,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 15,
    "young_price": 4.9,
    "discount_percent": 67,
    "discount_amount": 10.1,
    "advantage_type": "reduced_price",
    "age_min": 16,
    "age_max": 30,
    "student_required": false,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://toogoodtogo.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "BELIEBT",
      "SCHWEIZWEIT"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": "https://toogoodtogo.ch",
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 215,
    "click_count": 86,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111123",
    "slug": "eth-uzh-mensa-deus",
    "title_de": "ETH & UZH Mensen: Tagesmen\u00fcs ab CHF 6.90 mit Legi",
    "title_fr": "ETH & UZH Mensen: Tagesmen\u00fcs ab CHF 6.90 mit Legi",
    "title_it": "ETH & UZH Mensen: Tagesmen\u00fcs ab CHF 6.90 mit Legi",
    "description_de": "Rabattierte Men\u00fcpreise in den Hochschulmensen der SV Group gegen Vorweis der Legi.",
    "description_fr": "Rabattierte Men\u00fcpreise in den Hochschulmensen der SV Group gegen Vorweis der Legi.",
    "description_it": "Rabattierte Men\u00fcpreise in den Hochschulmensen der SV Group gegen Vorweis der Legi.",
    "conditions_de": "G\u00fcltige Legi der ETH Z\u00fcrich oder UZH.",
    "how_to_get_de": "1. Mensa Polyterrasse oder Irchel besuchen\n2. Legi an der Kasse vorweisen\n3. Rabattierten Preis zahlen",
    "brand_id": "b-sv",
    "brand": {
      "id": "b-sv",
      "slug": "sv-group",
      "name": "SV Group Mensen",
      "logo_url": null,
      "description_de": "Mensa-Betreiber an zahlreichen Schweizer Hochschulen und Universit\u00e4ten.",
      "website_url": "https://www.sv-group.ch",
      "categories": [
        "lifestyle"
      ],
      "created_at": "2026-09-26T02:48:56.626Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-lifestyle",
    "category": {
      "id": "cat-lifestyle",
      "slug": "lifestyle",
      "name_de": "Entertainment & Gaming",
      "name_fr": "Entertainment & Gaming",
      "name_it": "Entertainment & Gaming",
      "icon": "\ud83c\udfae",
      "description_de": "Angebote in Entertainment & Gaming",
      "sort_order": 5,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 16.5,
    "young_price": 6.9,
    "discount_percent": 58,
    "discount_amount": 9.6,
    "advantage_type": "reduced_price",
    "age_min": 18,
    "age_max": 30,
    "student_required": true,
    "city_id": "c-zurich",
    "canton": "ZH",
    "is_nationwide": false,
    "is_online": false,
    "external_url": "https://www.sv-group.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "ZUERICH",
      "STUDENTEN"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": "https://www.sv-group.ch",
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 240,
    "click_count": 98,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111124",
    "slug": "swisscovery-library",
    "title_de": "Swisscovery Bibliotheksnetz: Kostenloser Zugang",
    "title_fr": "Swisscovery Bibliotheksnetz: Kostenloser Zugang",
    "title_it": "Swisscovery Bibliotheksnetz: Kostenloser Zugang",
    "description_de": "Kostenloser Zugang zum Schweizer Bibliotheksnetzwerk Swisscovery f\u00fcr Studierende.",
    "description_fr": "Kostenloser Zugang zum Schweizer Bibliotheksnetzwerk Swisscovery f\u00fcr Studierende.",
    "description_it": "Kostenloser Zugang zum Schweizer Bibliotheksnetzwerk Swisscovery f\u00fcr Studierende.",
    "conditions_de": "Registrierung \u00fcber SLSP Swisscovery mit Switch edu-ID.",
    "how_to_get_de": "1. Swisscovery Portal \u00f6ffnen\n2. Mit Switch edu-ID anmelden\n3. Millionen Medien kostenlos ausleihen",
    "brand_id": "b-swisscovery",
    "brand": {
      "id": "b-swisscovery",
      "slug": "swisscovery",
      "name": "SLSP Swisscovery",
      "logo_url": null,
      "description_de": "Bibliotheksnetzwerk der Schweizer Hochschulen und Universit\u00e4ten.",
      "website_url": "https://swisscovery.slsp.ch",
      "categories": [
        "kultur"
      ],
      "created_at": "2026-09-26T02:48:56.626Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-kultur",
    "category": {
      "id": "cat-kultur",
      "slug": "kultur",
      "name_de": "Kultur & Events",
      "name_fr": "Kultur & Events",
      "name_it": "Kultur & Events",
      "icon": "\ud83c\udf9f\ufe0f",
      "description_de": "Angebote in Kultur & Events",
      "sort_order": 7,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": null,
    "young_price": null,
    "discount_percent": null,
    "discount_amount": null,
    "advantage_type": "free",
    "age_min": 16,
    "age_max": 30,
    "student_required": true,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://swisscovery.slsp.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "STUDENTEN",
      "GRATIS",
      "ONLINE"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": "https://swisscovery.slsp.ch",
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 105,
    "click_count": 38,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111125",
    "slug": "kulturlegi-caritas",
    "title_de": "Caritas KulturLegi: Bis zu 70% Rabatt auf Kultur & Sport",
    "title_fr": "Caritas KulturLegi: Bis zu 70% Rabatt auf Kultur & Sport",
    "title_it": "Caritas KulturLegi: Bis zu 70% Rabatt auf Kultur & Sport",
    "description_de": "KulturLegi der Caritas f\u00fcr Verg\u00fcnstigungen bei Kultur, Sport und Bildung bei geringem Einkommen.",
    "description_fr": "KulturLegi der Caritas f\u00fcr Verg\u00fcnstigungen bei Kultur, Sport und Bildung bei geringem Einkommen.",
    "description_it": "KulturLegi der Caritas f\u00fcr Verg\u00fcnstigungen bei Kultur, Sport und Bildung bei geringem Einkommen.",
    "conditions_de": "Nachweis eines geringen Einkommens gem\u00e4ss kantonalen Caritas-Kriterien.",
    "how_to_get_de": "1. Caritas Portal deiner Region aufrufen\n2. Ausbildungsnachweis & Lohnblatt einreichen\n3. KulturLegi Ausweis erhalten",
    "brand_id": "b-caritas",
    "brand": {
      "id": "b-caritas",
      "slug": "caritas",
      "name": "Caritas Schweiz",
      "logo_url": null,
      "description_de": "KulturLegi der Caritas f\u00fcr Verg\u00fcnstigungen bei Kultur und Sport.",
      "website_url": "https://www.kulturlegi.ch",
      "categories": [
        "kultur"
      ],
      "created_at": "2026-09-26T02:48:56.626Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-kultur",
    "category": {
      "id": "cat-kultur",
      "slug": "kultur",
      "name_de": "Kultur & Events",
      "name_fr": "Kultur & Events",
      "name_it": "Kultur & Events",
      "icon": "\ud83c\udf9f\ufe0f",
      "description_de": "Angebote in Kultur & Events",
      "sort_order": 7,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": null,
    "young_price": null,
    "discount_percent": 70,
    "discount_amount": null,
    "advantage_type": "discount_percent",
    "age_min": 16,
    "age_max": 30,
    "student_required": false,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.kulturlegi.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "SCHWEIZWEIT"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": "https://www.kulturlegi.ch",
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 135,
    "click_count": 44,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111126",
    "slug": "museumspass-ch",
    "title_de": "Schweizer Museumspass: CHF 120.\u2013 statt CHF 177.\u2013 f\u00fcr Studierende",
    "title_fr": "Schweizer Museumspass: CHF 120.\u2013 statt CHF 177.\u2013 f\u00fcr Studierende",
    "title_it": "Schweizer Museumspass: CHF 120.\u2013 statt CHF 177.\u2013 f\u00fcr Studierende",
    "description_de": "Schweizer Museumspass f\u00fcr freien Eintritt in \u00fcber 500 Museen und Schl\u00f6sser.",
    "description_fr": "Schweizer Museumspass f\u00fcr freien Eintritt in \u00fcber 500 Museen und Schl\u00f6sser.",
    "description_it": "Schweizer Museumspass f\u00fcr freien Eintritt in \u00fcber 500 Museen und Schl\u00f6sser.",
    "conditions_de": "Kostenloser Zutritt zu Museen gegen Vorweis der Legi.",
    "how_to_get_de": "1. Museumspass Online-Shop besuchen\n2. Studententarif w\u00e4hlen\n3. Ausweis hochladen",
    "brand_id": "b-museumspass",
    "brand": {
      "id": "b-museumspass",
      "slug": "museumspass",
      "name": "Schweizer Museumspass",
      "logo_url": null,
      "description_de": "Zugang zu \u00fcber 500 Museen und Schl\u00f6ssern in der ganzen Schweiz.",
      "website_url": "https://www.museumspass.ch",
      "categories": [
        "kultur"
      ],
      "created_at": "2026-09-26T02:48:56.626Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-kultur",
    "category": {
      "id": "cat-kultur",
      "slug": "kultur",
      "name_de": "Kultur & Events",
      "name_fr": "Kultur & Events",
      "name_it": "Kultur & Events",
      "icon": "\ud83c\udf9f\ufe0f",
      "description_de": "Angebote in Kultur & Events",
      "sort_order": 7,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 177,
    "young_price": 120,
    "discount_percent": 32,
    "discount_amount": 57,
    "advantage_type": "reduced_price",
    "age_min": 16,
    "age_max": 30,
    "student_required": true,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.museumspass.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "STUDENTEN",
      "SCHWEIZWEIT"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": "https://www.museumspass.ch",
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 160,
    "click_count": 55,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111127",
    "slug": "xbox-game-pass-ch",
    "title_de": "Xbox Game Pass PC: CHF 1.\u2013 im 1. Monat",
    "title_fr": "Xbox Game Pass PC: CHF 1.\u2013 im 1. Monat",
    "title_it": "Xbox Game Pass PC: CHF 1.\u2013 im 1. Monat",
    "description_de": "Zugang zu zahlreichen PC-Spielen mit dem Xbox Game Pass in der Schweiz.",
    "description_fr": "Zugang zu zahlreichen PC-Spielen mit dem Xbox Game Pass in der Schweiz.",
    "description_it": "Zugang zu zahlreichen PC-Spielen mit dem Xbox Game Pass in der Schweiz.",
    "conditions_de": "Aktionsangebot f\u00fcr Neukunden.",
    "how_to_get_de": "1. Microsoft Store CH aufrufen\n2. Xbox Game Pass PC w\u00e4hlen\n3. Erstmonat f\u00fcr CHF 1.\u2013 testen",
    "brand_id": "b-microsoft",
    "brand": {
      "id": "b-microsoft",
      "slug": "microsoft",
      "name": "Microsoft Gaming",
      "logo_url": null,
      "description_de": "Xbox Game Pass f\u00fcr PC und Konsolen in der Schweiz.",
      "website_url": "https://www.xbox.com/de-CH/",
      "categories": [
        "lifestyle"
      ],
      "created_at": "2026-09-26T02:48:56.626Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-lifestyle",
    "category": {
      "id": "cat-lifestyle",
      "slug": "lifestyle",
      "name_de": "Entertainment & Gaming",
      "name_fr": "Entertainment & Gaming",
      "name_it": "Entertainment & Gaming",
      "icon": "\ud83c\udfae",
      "description_de": "Angebote in Entertainment & Gaming",
      "sort_order": 5,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": 12.99,
    "young_price": 1.0,
    "discount_percent": 92,
    "discount_amount": 11.99,
    "advantage_type": "reduced_price",
    "age_min": 16,
    "age_max": 30,
    "student_required": false,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.xbox.com/de-CH/",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "BELIEBT",
      "ONLINE"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": "https://www.xbox.com",
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 270,
    "click_count": 112,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  },
  {
    "id": "b1111111-1111-4111-a111-111111111128",
    "slug": "neon-free-card-gratis",
    "title_de": "Neon Mastercard: Kostenlose Kreditkarte ohne Jahresgeb\u00fchr",
    "title_fr": "Neon Mastercard: Kostenlose Kreditkarte ohne Jahresgeb\u00fchr",
    "title_it": "Neon Mastercard: Kostenlose Kreditkarte ohne Jahresgeb\u00fchr",
    "description_de": "Kostenlose Neon Mastercard ohne Kontof\u00fchrungsgeb\u00fchr f\u00fcr junge Erwachsene.",
    "description_fr": "Kostenlose Neon Mastercard ohne Kontof\u00fchrungsgeb\u00fchr f\u00fcr junge Erwachsene.",
    "description_it": "Kostenlose Neon Mastercard ohne Kontof\u00fchrungsgeb\u00fchr f\u00fcr junge Erwachsene.",
    "conditions_de": "Wohnsitz in der Schweiz, Alter ab 16 Jahren.",
    "how_to_get_de": "1. Neon App installieren\n2. Ausweis verifizieren\n3. Physische Karte kostenlos per Post erhalten",
    "brand_id": "b-neon",
    "brand": {
      "id": "b-neon",
      "slug": "neon",
      "name": "Neon Bank",
      "logo_url": null,
      "description_de": "Schweizer Neobanking-L\u00f6sung mit geb\u00fchrenfreiem Girokonto und Mastercard.",
      "website_url": "https://www.neon-free.ch",
      "categories": [
        "finanzen"
      ],
      "created_at": "2026-09-26T02:48:56.626Z",
      "updated_at": "2026-09-26T02:48:56.626Z"
    },
    "category_id": "cat-finanzen",
    "category": {
      "id": "cat-finanzen",
      "slug": "finanzen",
      "name_de": "Finanzen & Banking",
      "name_fr": "Finanzen & Banking",
      "name_it": "Finanzen & Banking",
      "icon": "\ud83d\udcb3",
      "description_de": "Angebote in Finanzen & Banking",
      "sort_order": 2,
      "created_at": "2026-09-26T02:48:56.626Z"
    },
    "image_url": null,
    "logo_url": null,
    "normal_price": null,
    "young_price": null,
    "discount_percent": null,
    "discount_amount": null,
    "advantage_type": "free",
    "age_min": 16,
    "age_max": 30,
    "student_required": false,
    "city_id": null,
    "canton": null,
    "is_nationwide": true,
    "is_online": true,
    "external_url": "https://www.neon-free.ch",
    "affiliate_url": null,
    "discount_code": null,
    "start_date": "2026-09-26T02:48:56.626Z",
    "end_date": null,
    "status": "published",
    "tags": [
      "GRATIS",
      "ONLINE"
    ],
    "is_demo": false,
    "is_sponsored": false,
    "source_id": null,
    "source_url": "https://www.neon-free.ch",
    "checked_at": "2026-09-26T02:48:56.626Z",
    "verified_by": "JungVorteil Redaktion",
    "view_count": 175,
    "click_count": 70,
    "created_at": "2026-09-26T02:48:56.626Z",
    "updated_at": "2026-09-26T02:48:56.626Z"
  }
];

export async function getOffers(filters?: OfferFilters, page = 1, limit = 20): Promise<PaginatedOffers> {
  let filtered = [...FALLBACK_OFFERS];

  if (filters?.category_slug) {
    filtered = filtered.filter((o) => o.category?.slug === filters.category_slug);
  }
  if (filters?.city_slug) {
    filtered = filtered.filter((o) => o.is_nationwide || o.city?.slug === filters.city_slug);
  }
  if (filters?.brand_slug) {
    filtered = filtered.filter((o) => o.brand?.slug === filters.brand_slug);
  }
  if (filters?.advantage_type) {
    filtered = filtered.filter((o) => o.advantage_type === filters.advantage_type);
  }
  if (filters?.search) {
    const q = filters.search.toLowerCase();
    filtered = filtered.filter(
      (o) =>
        o.title_de.toLowerCase().includes(q) ||
        (o.description_de && o.description_de.toLowerCase().includes(q)) ||
        (o.brand && o.brand.name.toLowerCase().includes(q))
    );
  }

  const startIndex = (page - 1) * limit;
  const paginated = filtered.slice(startIndex, startIndex + limit);

  if (!isSupabaseConfigured()) {
    return {
      offers: paginated,
      total: filtered.length,
      page,
      limit,
      hasMore: startIndex + limit < filtered.length,
      total_pages: Math.ceil(filtered.length / limit),
    };
  }

  try {
    const supabase = await createClient();
    let query = supabase.from("offers").select("*, brand:brands(*), category:categories(*), city:cities(*)", { count: "exact" }).eq("status", "published");

    if (filters?.category_slug) {
      const { data: cat } = await supabase.from("categories").select("id").eq("slug", filters.category_slug).single();
      if (cat) query = query.eq("category_id", cat.id);
    }
    if (filters?.brand_slug) {
      const { data: br } = await supabase.from("brands").select("id").eq("slug", filters.brand_slug).single();
      if (br) query = query.eq("brand_id", br.id);
    }

    const { data, count, error } = await Promise.race([
      query.range(startIndex, startIndex + limit - 1),
      new Promise<{ data: null; count: null; error: Error }>((_, reject) => setTimeout(() => reject(new Error("Timeout")), 1000))
    ]);

    if (!error && data && data.length > 0) {
      const tot = count || data.length;
      return {
        offers: data as Offer[],
        total: tot,
        page,
        limit,
        hasMore: startIndex + limit < tot,
        total_pages: Math.ceil(tot / limit),
      };
    }
  } catch {}

  return {
    offers: paginated,
    total: filtered.length,
    page,
    limit,
    hasMore: startIndex + limit < filtered.length,
    total_pages: Math.ceil(filtered.length / limit),
  };
}

export async function getOfferBySlug(slug: string): Promise<Offer | null> {
  const normSlug = slug.toLowerCase().trim();
  const fallback = FALLBACK_OFFERS.find(
    (o) => o.slug.toLowerCase() === normSlug || o.id === slug
  ) || null;

  if (!isSupabaseConfigured()) return fallback;

  try {
    const supabase = await createClient();
    const { data } = await fetchWithTimeout(
      supabase
        .from("offers")
        .select("*, brand:brands(*), category:categories(*), city:cities(*)")
        .eq("slug", normSlug)
        .maybeSingle(),
      5000
    ).catch(() => ({ data: null }));

    if (data) return data as Offer;
  } catch (e) {
    console.error("getOfferBySlug error:", e);
  }

  return fallback;
}

export async function getTopOffers(limit = 6, page = 1): Promise<Offer[]> {
  const res = await getOffers(undefined, page, limit);
  return res.offers;
}

export async function getVerifiedStudentOffers(limit = 24, page = 1): Promise<Offer[]> {
  const all = await getOffers({ student: true, limit: 100 }).catch(() => ({ offers: [] }));
  const pool = all.offers && all.offers.length > 0 ? all.offers : FALLBACK_OFFERS;
  const filtered = pool.filter((o) => o.student_required || o.tags?.includes("STUDENTEN"));
  const res = filtered.length > 0 ? filtered : pool;
  return res.slice((page - 1) * limit, page * limit);
}

export async function getVerifiedUnderAgeOffers(maxAge = 30, limit = 24, page = 1): Promise<Offer[]> {
  const all = await getOffers({ limit: 100 }).catch(() => ({ offers: [] }));
  const pool = all.offers && all.offers.length > 0 ? all.offers : FALLBACK_OFFERS;
  const filtered = pool.filter((o) => !o.age_max || o.age_max <= maxAge);
  return filtered.slice((page - 1) * limit, page * limit);
}

export async function getVerifiedFreeOffers(limit = 24, page = 1): Promise<Offer[]> {
  const all = await getOffers({ advantage_type: "free", limit: 100 }).catch(() => ({ offers: [] }));
  const pool = all.offers && all.offers.length > 0 ? all.offers : FALLBACK_OFFERS;
  const filtered = pool.filter((o) => o.advantage_type === "free" || o.young_price === 0 || o.tags?.includes("KOSTENLOS") || o.tags?.includes("GRATIS"));
  const res = filtered.length > 0 ? filtered : pool;
  return res.slice((page - 1) * limit, page * limit);
}

export const getStudentOffers = getVerifiedStudentOffers;
export const getUnder25Offers = (limit = 24, page = 1) => getVerifiedUnderAgeOffers(25, limit, page);
export const getFreeOffers = getVerifiedFreeOffers;

export const getVerifiedOffers = getOffers;
export const getPublishedOffers = getOffers;
export const getVerifiedTopOffers = getTopOffers;
export const getVerifiedNewOffers = getTopOffers;
export const getVerifiedExpiringOffers = getTopOffers;
export const getVorteilDerWoche = async (...args: any[]) => FALLBACK_OFFERS[0];
export const getDemoOffers = async (...args: any[]) => FALLBACK_OFFERS;
export const incrementOfferView = async (...args: any[]) => {};

export async function searchOffers(query: string, limit = 10): Promise<Offer[]> {
  const q = query.toLowerCase();
  return FALLBACK_OFFERS.filter(o => o.title_de.toLowerCase().includes(q) || (o.description_de && o.description_de.toLowerCase().includes(q))).slice(0, limit);
}

export async function getSimilarOffers(offerId: string, limit = 4): Promise<Offer[]> {
  return FALLBACK_OFFERS.filter(o => o.id !== offerId).slice(0, limit);
}

export async function getOffersByCategory(categorySlug: string, limit = 12): Promise<Offer[]> {
  return FALLBACK_OFFERS.filter(o => o.category?.slug === categorySlug).slice(0, limit);
}

export async function getOffersByCity(citySlug: string, limit = 12): Promise<Offer[]> {
  return FALLBACK_OFFERS.filter(o => o.city?.slug === citySlug || o.is_nationwide).slice(0, limit);
}

export async function getOffersByBrand(brandSlug: string, limit = 12): Promise<Offer[]> {
  return FALLBACK_OFFERS.filter(o => o.brand?.slug === brandSlug).slice(0, limit);
}
