// config/categories.ts
import { Category } from "@/types";

export const CATEGORIES: Omit<Category, "id" | "created_at" | "offer_count">[] = [
  {
    slug: "handy",
    name_de: "Mobilfunk & Internet",
    name_fr: "Mobile & Internet",
    name_it: "Mobile & Internet",
    icon: "📱",
    description_de: "Handy-Tarife, SIM-Karten und Internet-Abos für Junge",
    sort_order: 1,
  },
  {
    slug: "reisen",
    name_de: "Reisen & ÖV",
    name_fr: "Voyages & TP",
    name_it: "Viaggi & TP",
    icon: "🚆",
    description_de: "Vergünstigte Zugtickets, Halbtax, GA und Reiseangebote",
    sort_order: 2,
  },
  {
    slug: "kino",
    name_de: "Kino & Unterhaltung",
    name_fr: "Cinéma & Divertissement",
    name_it: "Cinema & Intrattenimento",
    icon: "🎬",
    description_de: "Günstige Kinotickets und Unterhaltungsangebote",
    sort_order: 3,
  },
  {
    slug: "restaurants",
    name_de: "Essen & Restaurants",
    name_fr: "Nourriture & Restaurants",
    name_it: "Cibo & Ristoranti",
    icon: "🍔",
    description_de: "Rabatte in Restaurants, Fast Food und Cafés",
    sort_order: 4,
  },
  {
    slug: "mode",
    name_de: "Mode & Kleidung",
    name_fr: "Mode & Vêtements",
    name_it: "Moda & Abbigliamento",
    icon: "👕",
    description_de: "Studentenrabatte bei Mode und Kleidung",
    sort_order: 5,
  },
  {
    slug: "technik",
    name_de: "Technik & Software",
    name_fr: "Technologie & Logiciels",
    name_it: "Tecnologia & Software",
    icon: "💻",
    description_de: "Günstige Tech-Produkte und Software-Lizenzen",
    sort_order: 6,
  },
  {
    slug: "gaming",
    name_de: "Gaming",
    name_fr: "Jeux vidéo",
    name_it: "Gaming",
    icon: "🎮",
    description_de: "Spiele, Abos und Gaming-Equipment mit Rabatt",
    sort_order: 7,
  },
  {
    slug: "fitness",
    name_de: "Fitness & Sport",
    name_fr: "Fitness & Sport",
    name_it: "Fitness & Sport",
    icon: "🏋️",
    description_de: "Fitnessstudio-Mitgliedschaften und Sportrabatte",
    sort_order: 8,
  },
  {
    slug: "streaming",
    name_de: "Streaming & Musik",
    name_fr: "Streaming & Musique",
    name_it: "Streaming & Musica",
    icon: "🎵",
    description_de: "Günstige Streaming-Abos für Musik, Filme und Serien",
    sort_order: 9,
  },
  {
    slug: "bildung",
    name_de: "Studium & Bildung",
    name_fr: "Études & Formation",
    name_it: "Studio & Formazione",
    icon: "🎓",
    description_de: "Studentenrabatte auf Bücher, Kurse und Software",
    sort_order: 10,
  },
  {
    slug: "hotels",
    name_de: "Reisen & Hotels",
    name_fr: "Voyages & Hôtels",
    name_it: "Viaggi & Hotel",
    icon: "✈️",
    description_de: "Günstige Hotelbuchungen und Reiseangebote",
    sort_order: 11,
  },
  {
    slug: "finanzen",
    name_de: "Finanzen & Banking",
    name_fr: "Finances & Banque",
    name_it: "Finanze & Banca",
    icon: "💳",
    description_de: "Konten, Karten und Finanzprodukte für Junge",
    sort_order: 12,
  },
  {
    slug: "events",
    name_de: "Events & Konzerte",
    name_fr: "Événements & Concerts",
    name_it: "Eventi & Concerti",
    icon: "🎟️",
    description_de: "Günstige Tickets für Events, Konzerte und Messen",
    sort_order: 13,
  },
  {
    slug: "shopping",
    name_de: "Shopping & Lifestyle",
    name_fr: "Shopping & Style de vie",
    name_it: "Shopping & Lifestyle",
    icon: "🛍️",
    description_de: "Allgemeine Einkaufsrabatte und Gutscheine",
    sort_order: 14,
  },
  {
    slug: "gratis",
    name_de: "Kostenlos",
    name_fr: "Gratuit",
    name_it: "Gratuito",
    icon: "🆓",
    description_de: "Komplett kostenlose Angebote und Services",
    sort_order: 15,
  },
];
